classdef RoadsenseScenarioLibrarySystem < matlab.System
    %ROADSENSESCENARIOLIBRARYSYSTEM Emit selected route, truth, and events.
    methods (Access=protected)
        function varargout=stepImpl(~,currentTime,scenarioSelect)
            [s,a,z]=RoadsenseScenarioCatalog(double(scenarioSelect),currentTime);
            varargout={s.Timestamp,s.ScenarioID,s.Count,s.WorldPositions, ...
                s.RecommendedSpeeds,s.ValidMask,s.DesiredSpeed,s.SpeedLimit, ...
                s.GoalRadius,s.AllowObstacleAvoidance,s.UncontrolledIntersection, ...
                s.OccludedArea,s.MergeRequired,s.InitialPosition,s.InitialYaw, ...
                s.InitialSpeed,s.FrictionCoefficient,s.Grade,s.Bank, ...
                s.RollingResistance,s.Valid,a.Timestamp,a.Count,a.ActorIDs, ...
                a.ClassIDs,a.Positions,a.Velocities,a.Yaws,a.Dimensions, ...
                a.ValidMask,a.Overflow,a.Valid,z.Timestamp,z.ScenarioID, ...
                z.ElapsedTime,z.Duration,z.EventMask,z.ActiveActorCount,z.Valid};
        end
        function number=getNumInputsImpl(~); number=2; end
        function number=getNumOutputsImpl(~); number=39; end
        function names=getInputNamesImpl(~); names=["CurrentTime","ScenarioSelect"]; end
        function varargout=getOutputNamesImpl(~)
            names={'DefinitionTimestamp','DefinitionScenarioID','RouteCount', ...
                'WorldPositions','RecommendedSpeeds','RouteValidMask','DesiredSpeed', ...
                'SpeedLimit','GoalRadius','AllowObstacleAvoidance', ...
                'UncontrolledIntersection','OccludedArea','MergeRequired', ...
                'InitialPosition','InitialYaw','InitialSpeed','FrictionCoefficient', ...
                'Grade','Bank','RollingResistance','DefinitionValid','TruthTimestamp', ...
                'ActorCount','ActorIDs','ClassIDs','ActorPositions','ActorVelocities', ...
                'ActorYaws','ActorDimensions','ActorValidMask','ActorOverflow', ...
                'TruthValid','StatusTimestamp','StatusScenarioID','ElapsedTime', ...
                'Duration','EventMask','ActiveActorCount','StatusValid'};
            varargout=names;
        end
        function varargout=getOutputSizeImpl(~)
            one=[1 1]; varargout={one,one,one,[256 3],[256 1],[256 1], ...
                one,one,one,one,one,one,one,[3 1],one,one,one,one,one,one,one, ...
                one,one,[64 1],[64 1],[64 3],[64 3],[64 1],[64 3],[64 1], ...
                one,one,one,one,one,one,one,one,one};
        end
        function varargout=getOutputDataTypeImpl(~)
            varargout={'double','uint16','uint16','double','single','logical', ...
                'single','single','single','logical','logical','logical','logical', ...
                'double','double','single','single','single','single','single', ...
                'logical','double','uint16','uint32','uint8','double','single', ...
                'single','single','logical','logical','logical','double','uint16', ...
                'single','single','uint16','uint16','logical'};
        end
        function varargout=isOutputFixedSizeImpl(~); varargout=repmat({true},1,39); end
        function varargout=isOutputComplexImpl(~); varargout=repmat({false},1,39); end
        function icon=getIconImpl(~); icon="Roadsense\n5 Scenarios + Demo"; end
    end
end
