function modelPath = createRoadsenseMotionPredictionModel()
%CREATEROADSENSEMOTIONPREDICTIONMODEL Generate the prediction component.

componentDir = fileparts(mfilename("fullpath"));
root = fileparts(fileparts(componentDir));
modelName = "Roadsense_MotionPrediction";
modelPath = fullfile(componentDir,modelName + ".slx");

addpath(fullfile(root,"Models","SharedData"));
addpath(componentDir);
addpath(fullfile(root,"Data"));
createRoadsenseDataDictionary(fullfile(root,"Data","Roadsense_Data.sldd"));

if bdIsLoaded(modelName); close_system(modelName,0); end
if isfile(modelPath); delete(modelPath); end
new_system(modelName,"Model");
cleanup = onCleanup(@() closeIfLoaded(modelName));
set_param(modelName,"DataDictionary","Roadsense_Data.sldd", ...
    "SolverType","Fixed-step","Solver","FixedStepDiscrete", ...
    "FixedStep","RsTsBase","StopTime","1.0","SignalLogging","on");

add_block("simulink/Ports & Subsystems/In1",modelName + "/FusedTracks", ...
    "Position",[30 185 60 205],"OutDataTypeStr","Bus: RsFusedTrackListBus", ...
    "PortDimensions","1","SampleTime","RsTsPlanning");
add_block("simulink/Signal Routing/Bus Selector",modelName + "/Track Timestamp", ...
    "Position",[110 80 115 135],"OutputSignals","Timestamp");

predictionBlock = modelName + "/History Adaptive Multimodal Predictor";
add_block("simulink/User-Defined Functions/MATLAB System",predictionBlock, ...
    "Position",[205 135 485 310]);
set_param(predictionBlock,"System","RoadsenseMotionPredictionSystem", ...
    "SimulateUsing","Interpreted execution");
set_param(predictionBlock, ...
    "MaxTracks","double(RsMaxTracks)", ...
    "MaxModes","double(RsMaxPredictionModes)", ...
    "PredictionSteps","double(RsPredictionSteps)", ...
    "PredictionStep","RsPredictionStep", ...
    "HistoryGain","RsPredictionHistoryGain", ...
    "VehicleTurnRate","RsPredictionVehicleTurnRate", ...
    "VulnerableTurnRate","RsPredictionVulnerableTurnRate", ...
    "VehicleBrake","RsPredictionVehicleBrake", ...
    "VulnerableBrake","RsPredictionVulnerableBrake", ...
    "MinimumModeProbability","RsPredictionMinimumModeProbability");

add_block("simulink/Signal Routing/Bus Creator",modelName + "/Prediction Bus", ...
    "Position",[620 75 630 360],"Inputs","15", ...
    "OutDataTypeStr","Bus: RsMotionPredictionListBus");
add_block("simulink/Ports & Subsystems/Out1",modelName + "/Predictions", ...
    "Position",[725 205 755 225], ...
    "OutDataTypeStr","Bus: RsMotionPredictionListBus");

add_line(modelName,"FusedTracks/1","Track Timestamp/1","autorouting","on");
add_line(modelName,"FusedTracks/1","History Adaptive Multimodal Predictor/1","autorouting","on");
add_line(modelName,"Track Timestamp/1","Prediction Bus/1","autorouting","on");
predictionNames=["Count","TrackIDs","ClassIDs","NumModes","NumSteps", ...
    "TimeOffsets","ModeProbabilities","Positions","Yaws","PositionCovariances", ...
    "ValidMask","ProcessingTime","Overflow","Valid"];
for port = 1:14
    line=add_line(modelName,"History Adaptive Multimodal Predictor/" + port, ...
        "Prediction Bus/" + (port+1),"autorouting","on");
    set_param(line,"Name",predictionNames(port));
end
add_line(modelName,"Prediction Bus/1","Predictions/1","autorouting","on");

annotation = Simulink.Annotation(modelName, ...
    "Roadsense Motion Prediction" + newline + ...
    "History-adaptive, class-aware modes with uncertainty growth" + newline + ...
    "continue | stop | left deviation | right deviation");
annotation.Position = [190 25 600 70];

applyRoadsenseModelStyle(modelName);
save_system(modelName,modelPath);
clear cleanup
close_system(modelName,0);
fprintf("Generated %s\n",modelPath);
end

function closeIfLoaded(modelName)
if bdIsLoaded(modelName); close_system(modelName,0); end
end
