function tracks = createSyntheticRoadsenseTrackList(time,carSpeed)
%CREATESYNTHETICROADSENSETRACKLIST Deterministic fused tracks for prediction.

arguments
    time (1,1) double = 0
    carSpeed (1,1) double = 4.0+0.3*time
end

maximum = 128;
count = 5;
turnRate = 0.20;
autoSpeed = 3.0;
if abs(turnRate) > eps
    autoPosition = [10+autoSpeed/turnRate*sin(turnRate*time), ...
        2+autoSpeed/turnRate*(1-cos(turnRate*time)),0.9];
else
    autoPosition = [10+autoSpeed*time,2,0.9];
end

positions = [5+4*time+0.15*time^2,-1.5,0.8; ...
    autoPosition; ...
    18,-3+1.2*time,0.9; ...
    23+0.7*time,4+0.8*time,0.7; ...
    14,6,0.5];
velocities = [carSpeed,0,0; ...
    autoSpeed*cos(turnRate*time),autoSpeed*sin(turnRate*time),0; ...
    0,1.2,0; ...
    0.7,0.8,0; ...
    0,0,0];
yaws = atan2(velocities(:,2),velocities(:,1));
yaws(end) = 0;

tracks = struct( ...
    "Timestamp",time, ...
    "Count",uint16(count), ...
    "TrackIDs",zeros(maximum,1,"uint32"), ...
    "ClassIDs",zeros(maximum,1,"uint8"), ...
    "ClassConfidences",zeros(maximum,1,"single"), ...
    "ExistenceProbabilities",zeros(maximum,1,"single"), ...
    "Positions",zeros(maximum,3,"single"), ...
    "Velocities",zeros(maximum,3,"single"), ...
    "Accelerations",zeros(maximum,3,"single"), ...
    "Yaws",zeros(maximum,1,"single"), ...
    "YawRates",zeros(maximum,1,"single"), ...
    "Dimensions",zeros(maximum,3,"single"), ...
    "StateCovariances",zeros(6,6,maximum,"single"), ...
    "Ages",zeros(maximum,1,"uint16"), ...
    "SensorMasks",zeros(maximum,1,"uint8"), ...
    "IsConfirmed",false(maximum,1), ...
    "ValidMask",false(maximum,1), ...
    "ProcessingTime",single(0.01), ...
    "SourceOverflow",false, ...
    "Overflow",false, ...
    "Valid",true);

tracks.TrackIDs(1:count) = uint32((101:105).');
tracks.ClassIDs(1:count) = uint8([1;4;7;9;10]);
tracks.ClassConfidences(1:count) = single([0.95;0.88;0.92;0.75;0.98]);
tracks.ExistenceProbabilities(1:count) = single([0.99;0.96;0.93;0.72;0.99]);
tracks.Positions(1:count,:) = single(positions);
tracks.Velocities(1:count,:) = single(velocities);
tracks.Yaws(1:count) = single(yaws);
tracks.Dimensions(1:count,:) = single([4.4 1.8 1.6;2.8 1.4 1.8; ...
    0.6 0.6 1.75;1.4 0.6 1.0;1.0 1.0 1.0]);
for index = 1:count
    tracks.StateCovariances(:,:,index) = single(diag([0.08 0.08 0.12 0.20 0.20 0.25]));
end
tracks.Ages(1:count) = uint16(20);
tracks.SensorMasks(1:count) = uint8(7);
tracks.IsConfirmed(1:count) = true;
tracks.ValidMask(1:count) = true;
end
