function modelPath = createRoadsenseLidarPerceptionModel()
%CREATEROADSENSELIDARPERCEPTIONMODEL Generate the LiDAR Simulink component.

componentDir = fileparts(mfilename("fullpath"));
root = fileparts(fileparts(componentDir));
modelName = "Roadsense_LidarPerception";
modelPath = fullfile(componentDir,modelName + ".slx");

addpath(fullfile(root,"Models","SharedData"));
addpath(componentDir);
addpath(fullfile(root,"Data"));
createRoadsenseDataDictionary(fullfile(root,"Data","Roadsense_Data.sldd"));

if bdIsLoaded(modelName)
    close_system(modelName,0);
end
if isfile(modelPath)
    delete(modelPath);
end
new_system(modelName,"Model");
cleanup = onCleanup(@() closeIfLoaded(modelName));

set_param(modelName, ...
    "DataDictionary","Roadsense_Data.sldd", ...
    "SolverType","Fixed-step", ...
    "Solver","FixedStepDiscrete", ...
    "FixedStep","RsTsBase", ...
    "StopTime","0.1", ...
    "SignalLogging","on");

add_block("simulink/Ports & Subsystems/In1",modelName + "/LidarFrame", ...
    "Position",[25 210 55 230], ...
    "OutDataTypeStr","Bus: RsLidarFrameBus", ...
    "PortDimensions","1","SampleTime","RsTsLidarPerception");
add_block("simulink/Signal Routing/Bus Selector",modelName + "/Lidar Frame Selector", ...
    "Position",[105 145 110 300], ...
    "OutputSignals","Timestamp,FrameID,Count,Points,Overflow,Valid");

systemBlock = modelName + "/Ground Surface and Obstacle Processing";
add_block("simulink/User-Defined Functions/MATLAB System",systemBlock, ...
    "Position",[205 125 440 335]);
set_param(systemBlock,"System","RoadsenseLidarPerceptionSystem", ...
    "SimulateUsing","Interpreted execution");

add_block("simulink/Signal Routing/Bus Creator",modelName + "/Grid Evidence Bus", ...
    "Position",[590 60 600 280], ...
    "Inputs","13", ...
    "OutDataTypeStr","Bus: RsLidarGridEvidenceBus");
add_block("simulink/Signal Routing/Bus Creator",modelName + "/Lidar Objects Bus", ...
    "Position",[590 340 600 580], ...
    "Inputs","14", ...
    "OutDataTypeStr","Bus: RsLidarObjectListBus");

add_block("simulink/Sources/Constant",modelName + "/Grid Resolution", ...
    "Position",[455 50 545 75],"Value","RsGridResolution","OutDataTypeStr","single");
add_block("simulink/Sources/Constant",modelName + "/Grid X Limits", ...
    "Position",[455 82 545 107],"Value","RsGridXLimits","OutDataTypeStr","single");
add_block("simulink/Sources/Constant",modelName + "/Grid Y Limits", ...
    "Position",[455 114 545 139],"Value","RsGridYLimits","OutDataTypeStr","single");

add_block("simulink/Ports & Subsystems/Out1",modelName + "/GridEvidence", ...
    "Position",[690 155 720 175], ...
    "OutDataTypeStr","Bus: RsLidarGridEvidenceBus");
add_block("simulink/Ports & Subsystems/Out1",modelName + "/LidarObjects", ...
    "Position",[690 445 720 465], ...
    "Port","2", ...
    "OutDataTypeStr","Bus: RsLidarObjectListBus");

add_line(modelName,"LidarFrame/1","Lidar Frame Selector/1","autorouting","on");
add_line(modelName,"Lidar Frame Selector/4","Ground Surface and Obstacle Processing/1","autorouting","on");
add_line(modelName,"Lidar Frame Selector/3","Ground Surface and Obstacle Processing/2","autorouting","on");
add_line(modelName,"Lidar Frame Selector/5","Ground Surface and Obstacle Processing/3","autorouting","on");
add_line(modelName,"Lidar Frame Selector/6","Ground Surface and Obstacle Processing/4","autorouting","on");

gridSources=["Lidar Frame Selector/1","Lidar Frame Selector/2","Grid Resolution/1", ...
    "Grid X Limits/1","Grid Y Limits/1", ...
    "Ground Surface and Obstacle Processing/"+(1:6), ...
    "Ground Surface and Obstacle Processing/16", ...
    "Ground Surface and Obstacle Processing/18"];
gridNames=["Timestamp","FrameID","Resolution","XLimits","YLimits", ...
    "Occupancy","GroundHeight","Roughness","PotholeProbability", ...
    "SurfaceCost","ObservedMask","ProcessingTime","Valid"];
connectBus(modelName,gridSources,"Grid Evidence Bus",gridNames);

objectSources=["Lidar Frame Selector/1","Lidar Frame Selector/2", ...
    "Ground Surface and Obstacle Processing/"+(7:18)];
objectNames=["Timestamp","FrameID","Count","Positions","Dimensions","Yaws", ...
    "ClassIDs","Scores","PositionCovariances","PointCounts","ValidMask", ...
    "ProcessingTime","Overflow","Valid"];
connectBus(modelName,objectSources,"Lidar Objects Bus",objectNames);

add_line(modelName,"Grid Evidence Bus/1","GridEvidence/1","autorouting","on");
add_line(modelName,"Lidar Objects Bus/1","LidarObjects/1","autorouting","on");

annotation = Simulink.Annotation(modelName, ...
    "Roadsense LiDAR Perception" + newline + ...
    "SMRF ground and surface analysis with geometric obstacle clustering");
annotation.Position = [205 25 560 60];

save_system(modelName,modelPath);
clear cleanup
close_system(modelName,0);
fprintf("Generated %s\n",modelPath);
end

function connectBus(modelName,sources,busName,names)
for index=1:numel(sources)
    line=add_line(modelName,sources(index),busName+"/"+index,"autorouting","on");
    sourceBlock=extractBefore(sources(index),"/"+extractAfter(sources(index),"/"));
    if ~strcmp(get_param(modelName+"/"+sourceBlock,"BlockType"),"BusSelector")
        set_param(line,"Name",names(index));
    end
end
end

function closeIfLoaded(modelName)
if bdIsLoaded(modelName)
    close_system(modelName,0);
end
end
