function modelPath = createRoadsenseSemanticMapFusionModel()
%CREATEROADSENSESEMANTICMAPFUSIONMODEL Generate the map-fusion component.

componentDir = fileparts(mfilename("fullpath"));
root = fileparts(fileparts(componentDir));
modelName = "Roadsense_SemanticMapFusion";
modelPath = fullfile(componentDir,modelName + ".slx");

addpath(fullfile(root,"Models","SharedData"));
addpath(componentDir);
addpath(fullfile(root,"Data"));
createRoadsenseDataDictionary(fullfile(root,"Data","Roadsense_Data.sldd"));
if bdIsLoaded(modelName); close_system(modelName,0); end
if isfile(modelPath); delete(modelPath); end
new_system(modelName,"Model");
cleanup = onCleanup(@() closeIfLoaded(modelName));
set_param(modelName,"DataDictionary","Roadsense_Data.sldd", ...
    "SolverType","Fixed-step","Solver","FixedStepDiscrete", ...
    "FixedStep","RsTsBase","StopTime","1.0","SignalLogging","on");

inputNames = ["ImageSemantic","LidarGrid","FusedTracks","Predictions"];
inputTypes = ["Bus: RsImageSemanticBus","Bus: RsLidarGridEvidenceBus", ...
    "Bus: RsFusedTrackListBus","Bus: RsMotionPredictionListBus"];
for index = 1:numel(inputNames)
    vertical = 105+(index-1)*70;
    add_block("simulink/Ports & Subsystems/In1",modelName + "/" + inputNames(index), ...
        "Position",[25 vertical 55 vertical+20],"Port",string(index), ...
        "OutDataTypeStr",inputTypes(index),"PortDimensions","1", ...
        "SampleTime","RsTsPlanning");
end

fusionBlock = modelName + "/Camera Lidar Track and Prediction Fusion";
add_block("simulink/User-Defined Functions/MATLAB System",fusionBlock, ...
    "Position",[180 100 485 370]);
set_param(fusionBlock,"System","RoadsenseSemanticMapFusionSystem", ...
    "SimulateUsing","Interpreted execution");
set_param(fusionBlock, ...
    "GridRows","double(RsGridRows)","GridCols","double(RsGridCols)", ...
    "SemanticRows","double(RsSemanticOutputHeight)", ...
    "SemanticCols","double(RsSemanticOutputWidth)", ...
    "MaxTracks","double(RsMaxTracks)","MaxModes","double(RsMaxPredictionModes)", ...
    "PredictionSteps","double(RsPredictionSteps)", ...
    "GridResolution","RsGridResolution","GridXLimits","RsGridXLimits", ...
    "GridYLimits","RsGridYLimits","CameraFocalLength","RsCameraFocalLength", ...
    "CameraPrincipalPoint","RsCameraPrincipalPoint", ...
    "CameraHeight","RsCameraHeight","CameraPitchDown","RsCameraPitchDown", ...
    "UnknownDrivability","RsMapUnknownDrivability", ...
    "CameraMinConfidence","RsMapCameraMinConfidence", ...
    "CurrentSafetyMargin","RsMapCurrentSafetyMargin", ...
    "MaximumCurrentInflation","RsMapMaximumCurrentInflation", ...
    "PredictionSigma","RsMapPredictionSigma", ...
    "MaximumPredictionRadius","RsMapMaximumPredictionRadius", ...
    "PredictionTimeDecay","RsMapPredictionTimeDecay", ...
    "PotholeThreshold","RsMapPotholeThreshold");

add_block("simulink/Signal Routing/Bus Creator",modelName + "/Semantic Grid Bus", ...
    "Position",[620 75 630 395],"Inputs","16", ...
    "OutDataTypeStr","Bus: RsSemanticGridBus");
add_block("simulink/Ports & Subsystems/Out1",modelName + "/SemanticGrid", ...
    "Position",[730 220 760 240],"OutDataTypeStr","Bus: RsSemanticGridBus");

for index = 1:numel(inputNames)
    add_line(modelName,inputNames(index)+"/1", ...
        "Camera Lidar Track and Prediction Fusion/"+index,"autorouting","on");
end
gridNames=["Timestamp","Resolution","XLimits","YLimits","StaticOccupancy", ...
    "DynamicOccupancy","PredictedRisk","Occupancy","Drivability","SurfaceCost", ...
    "CombinedCost","SemanticLabel","ObservedMask","ProcessingTime", ...
    "SourceOverflow","Valid"];
for port = 1:16
    line=add_line(modelName,"Camera Lidar Track and Prediction Fusion/"+port, ...
        "Semantic Grid Bus/"+port,"autorouting","on");
    set_param(line,"Name",gridNames(port));
end
add_line(modelName,"Semantic Grid Bus/1","SemanticGrid/1","autorouting","on");

annotation = Simulink.Annotation(modelName, ...
    "Roadsense Semantic Map Fusion" + newline + ...
    "Ground-projected camera semantics + LiDAR terrain + current and predicted objects" + newline + ...
    "Unknown space receives a conservative cost instead of being assumed free");
annotation.Position = [175 25 700 72];
save_system(modelName,modelPath);
clear cleanup
close_system(modelName,0);
fprintf("Generated %s\n",modelPath);
end

function closeIfLoaded(modelName)
if bdIsLoaded(modelName); close_system(modelName,0); end
end
