function modelPath=createRoadsenseScenarioSensorSourceModel()
%CREATEROADSENSESCENARIOSENSORSOURCEMODEL Generate synthetic sensor source.
componentDir=fileparts(mfilename("fullpath")); root=fileparts(fileparts(componentDir));
modelName="Roadsense_ScenarioSensorSource"; modelPath=fullfile(componentDir,modelName+".slx");
addpath(genpath(fullfile(root,"Models"))); addpath(fullfile(root,"Data"));
createRoadsenseDataDictionary(fullfile(root,"Data","Roadsense_Data.sldd"));
if bdIsLoaded(modelName); close_system(modelName,0); end
if isfile(modelPath); delete(modelPath); end
new_system(modelName,"Model"); cleanup=onCleanup(@() closeIfLoaded(modelName));
set_param(modelName,"DataDictionary","Roadsense_Data.sldd","SolverType","Fixed-step", ...
    "Solver","FixedStepDiscrete","FixedStep","RsTsBase","StopTime","25", ...
    "SignalLogging","on","ScreenColor","white","ZoomFactor","FitSystem");

inputNames=["CurrentTime","EgoState","TruthActors","ScenarioDefinition","ScenarioStatus"];
inputTypes=["double","Bus: RsEgoStateBus","Bus: RsScenarioActorListBus", ...
    "Bus: RsScenarioDefinitionBus","Bus: RsScenarioStatusBus"];
inputTags=["RsSensorTime","RsSensorEgo","RsSensorTruth","RsSensorDefinition","RsScenarioStatus"];
inputY=[205 315 425 535 645];
for index=1:5
    add_block("simulink/Ports & Subsystems/In1",modelName+"/"+inputNames(index), ...
        "Position",[40 inputY(index) 70 inputY(index)+20],"Port",string(index), ...
        "OutDataTypeStr",inputTypes(index),"SampleTime","RsTsScenario", ...
        "BackgroundColor","lightBlue");
    add_block("simulink/Signal Routing/Goto",modelName+"/"+inputTags(index), ...
        "Position",[125 inputY(index)-5 245 inputY(index)+25], ...
        "GotoTag",inputTags(index),"ShowName","off");
    wire(modelName,inputNames(index)+"/1",inputTags(index)+"/1",inputNames(index));
end

camera=modelName+"/Camera Sensor Model";
lidar=modelName+"/LiDAR Sensor Model";
radar=modelName+"/Radar Sensor Model";
addSensorSubsystem(camera,"RoadsenseScenarioCameraSystem",5,5,[380 135 690 330],"[0.72 0.87 1.00]");
addSensorSubsystem(lidar,"RoadsenseScenarioLidarSystem",5,8,[380 430 690 675],"[0.75 0.92 0.76]");
addSensorSubsystem(radar,"RoadsenseScenarioRadarSystem",5,11,[380 785 690 1085],"[1.00 0.83 0.58]");
set_param(camera+"/Sensor Algorithm","HorizontalFOV","RsScenarioCameraHorizontalFOV", ...
    "MaximumRange","RsScenarioCameraRange","FocalLength","RsCameraFocalLength", ...
    "PrincipalPoint","RsCameraPrincipalPoint","CameraHeight","RsCameraHeight", ...
    "PitchDown","RsCameraPitchDown");
set_param(lidar+"/Sensor Algorithm","MaximumRange","RsScenarioLidarRange", ...
    "MaximumPoints","double(RsMaxLidarPoints)");
set_param(radar+"/Sensor Algorithm","MaximumRange","RsScenarioRadarRange", ...
    "PositionSigma","RsScenarioRadarPositionSigma", ...
    "VelocitySigma","RsScenarioRadarVelocitySigma");
connectTaggedInputs(modelName,camera,[245 163],inputTags);
connectTaggedInputs(modelName,lidar,[245 458],inputTags);
connectTaggedInputs(modelName,radar,[245 813],inputTags);

rawNames=["CameraImage","CameraValid","LidarPoints","LidarIntensity","LidarCount", ...
    "LidarOverflow","LidarValid","RadarPositions","RadarVelocities", ...
    "RadarPositionCovariances","RadarVelocityCovariances","RadarScores", ...
    "RadarCount","RadarOverflow","RadarValid"];
rawTypes=["uint8","boolean","single","single","uint32","boolean","boolean", ...
    "single","single","single","single","single","uint16","boolean","boolean"];
rawDims={"[480 640 3]","1","[120000 3]","[120000 1]","1","1","1", ...
    "[256 3]","[256 3]","[3 3 256]","[3 3 256]","[256 1]","1","1","1"};
rawSources=["Camera Sensor Model/1","Camera Sensor Model/2", ...
    "LiDAR Sensor Model/1","LiDAR Sensor Model/2","LiDAR Sensor Model/3", ...
    "LiDAR Sensor Model/4","LiDAR Sensor Model/5", ...
    "Radar Sensor Model/1","Radar Sensor Model/2","Radar Sensor Model/3", ...
    "Radar Sensor Model/4","Radar Sensor Model/5","Radar Sensor Model/6", ...
    "Radar Sensor Model/7","Radar Sensor Model/8"];
outputY=[155 220 445 495 545 595 645 800 845 890 935 980 1025 1070 1115];
for index=1:numel(rawNames)
    add_block("simulink/Ports & Subsystems/Out1",modelName+"/"+rawNames(index), ...
        "Position",[1035 outputY(index) 1065 outputY(index)+20],"Port",string(index), ...
        "OutDataTypeStr",rawTypes(index),"PortDimensions",rawDims{index});
    wire(modelName,rawSources(index),rawNames(index)+"/1",rawNames(index));
end

metricTags=["CameraCount","CameraOccluded","CameraDropout", ...
    "LidarCountVisible","LidarOccluded","LidarDropout", ...
    "RadarCountVisible","RadarOccluded","RadarDropout"];
metricSources=["Camera Sensor Model/3","Camera Sensor Model/4","Camera Sensor Model/5", ...
    "LiDAR Sensor Model/6","LiDAR Sensor Model/7","LiDAR Sensor Model/8", ...
    "Radar Sensor Model/9","Radar Sensor Model/10","Radar Sensor Model/11"];
metricY=[345 375 405 690 720 750 1100 1130 1160];
for index=1:numel(metricTags)
    add_block("simulink/Signal Routing/Goto",modelName+"/"+metricTags(index), ...
        "Position",[750 metricY(index) 875 metricY(index)+24], ...
        "GotoTag",metricTags(index),"ShowName","off");
    wire(modelName,metricSources(index),metricTags(index)+"/1",metricTags(index));
end

health=modelName+"/Sensor Source Health";
addHealthSubsystem(health,[430 1245 760 1470]);
healthTags=["RsSensorTime","RsScenarioStatus", ...
    "CameraCount","LidarCountVisible","RadarCountVisible", ...
    "CameraOccluded","LidarOccluded","RadarOccluded", ...
    "CameraDropout","LidarDropout","RadarDropout"];
connectTaggedInputs(modelName,health,[295 1258],healthTags);
add_block("simulink/Ports & Subsystems/Out1",modelName+"/SensorStatus", ...
    "Position",[1035 1345 1065 1365],"Port","16", ...
    "OutDataTypeStr","Bus: RsScenarioSensorStatusBus");
wire(modelName,"Sensor Source Health/1","SensorStatus/1","SensorStatus");

title=Simulink.Annotation(modelName,"ROADSENSE  |  MULTI-SENSOR SCENARIO SOURCE");
title.Position=[335 20 825 55]; title.FontSize=16; title.FontWeight="bold";
subtitle=Simulink.Annotation(modelName,sprintf([ ...
    'Ground truth -> ego-frame camera, LiDAR and radar measurements\n' ...
    'FOV + range + occlusion + deterministic noise + dropout + road damage']));
subtitle.Position=[335 65 860 120]; subtitle.FontSize=11;
legendNote=Simulink.Annotation(modelName,sprintf([ ...
    'BLUE  camera image\nGREEN  LiDAR cloud\nORANGE  radar detections\nGREY  source health']));
legendNote.Position=[790 1245 1015 1345]; legendNote.FontSize=9;
set_param(modelName,"Location",[70 35 1510 930]);
applyRoadsenseModelStyle(modelName);
save_system(modelName,modelPath); clear cleanup; close_system(modelName,0);
fprintf("Generated %s\n",modelPath);
end

function addSensorSubsystem(path,systemClass,inputCount,outputCount,position,color)
add_block("simulink/Ports & Subsystems/Subsystem",path,"Position",position, ...
    "BackgroundColor",color,"FontWeight","bold","FontSize","11");
set_param(path,"ContentPreviewEnabled","off"); Simulink.SubSystem.deleteContents(path);
height=max(280,55*max(inputCount,outputCount));
for index=1:inputCount
    y=40+(index-1)*55;
    add_block("simulink/Ports & Subsystems/In1",path+"/Input"+index, ...
        "Position",[25 y 55 y+20],"Port",string(index));
end
add_block("simulink/User-Defined Functions/MATLAB System",path+"/Sensor Algorithm", ...
    "Position",[150 30 395 height-20],"BackgroundColor",color);
set_param(path+"/Sensor Algorithm","System",systemClass,"SimulateUsing","Interpreted execution");
for index=1:outputCount
    y=35+(index-1)*45;
    add_block("simulink/Ports & Subsystems/Out1",path+"/Output"+index, ...
        "Position",[500 y 530 y+20],"Port",string(index));
end
for index=1:inputCount; wire(path,"Input"+index+"/1","Sensor Algorithm/"+index,""); end
for index=1:outputCount; wire(path,"Sensor Algorithm/"+index,"Output"+index+"/1",""); end
end

function addHealthSubsystem(path,position)
add_block("simulink/Ports & Subsystems/Subsystem",path,"Position",position, ...
    "BackgroundColor","[0.88 0.88 0.88]","FontWeight","bold","FontSize","11");
set_param(path,"ContentPreviewEnabled","off"); Simulink.SubSystem.deleteContents(path);
for index=1:11
    y=35+(index-1)*42;
    add_block("simulink/Ports & Subsystems/In1",path+"/Input"+index, ...
        "Position",[20 y 50 y+20],"Port",string(index));
end
add_block("simulink/User-Defined Functions/MATLAB System",path+"/Health Logic", ...
    "Position",[130 45 355 475],"BackgroundColor","[0.88 0.88 0.88]");
set_param(path+"/Health Logic","System","RoadsenseScenarioSensorStatusSystem", ...
    "SimulateUsing","Interpreted execution");
add_block("simulink/Signal Routing/Bus Creator",path+"/Status Bus", ...
    "Position",[455 45 465 455],"Inputs","10", ...
    "OutDataTypeStr","Bus: RsScenarioSensorStatusBus");
names=["Timestamp","ScenarioID","CameraVisibleCount","LidarVisibleCount", ...
    "RadarVisibleCount","OccludedCount","CameraDropout","LidarDropout", ...
    "RadarDropout","Valid"];
for index=1:11; wire(path,"Input"+index+"/1","Health Logic/"+index,""); end
for index=1:10; wire(path,"Health Logic/"+index,"Status Bus/"+index,names(index)); end
add_block("simulink/Ports & Subsystems/Out1",path+"/SensorStatus", ...
    "Position",[550 235 580 255],"OutDataTypeStr","Bus: RsScenarioSensorStatusBus");
wire(path,"Status Bus/1","SensorStatus/1","SensorStatus");
end

function connectTaggedInputs(system,destination,startPosition,tags)
for index=1:numel(tags)
    y=startPosition(2)+(index-1)*31;
    name=string(get_param(destination,"Name"))+"_"+tags(index);
    add_block("simulink/Signal Routing/From",system+"/"+name, ...
        "Position",[startPosition(1) y startPosition(1)+125 y+20], ...
        "GotoTag",tags(index),"ShowName","off");
    wire(system,name+"/1",string(get_param(destination,"Name"))+"/"+index,"");
end
end
function wire(system,source,destination,name)
line=add_line(system,source,destination,"autorouting","on");
if strlength(name)>0; set_param(line,"Name",name); end
end
function closeIfLoaded(modelName)
if bdIsLoaded(modelName); close_system(modelName,0); end
end
