function data=createSyntheticRoadsenseScenarioSensorInputs(scenarioID,time)
%CREATESYNTHETICROADSENSESCENARIOSENSORINPUTS Build deterministic source inputs.
arguments
    scenarioID (1,1) double = 1
    time (1,1) double = 7
end
[definition,truth,status]=RoadsenseScenarioCatalog(scenarioID,time);
data=struct("CurrentTime",time,"ScenarioDefinition",definition, ...
    "TruthActors",truth,"ScenarioStatus",status);
data.EgoState=struct("Timestamp",time,"Position",definition.InitialPosition, ...
    "Velocity",[double(definition.InitialSpeed)*cos(definition.InitialYaw); ...
    double(definition.InitialSpeed)*sin(definition.InitialYaw);0], ...
    "Acceleration",[0;0;0],"Yaw",definition.InitialYaw,"Pitch",0,"Roll",0, ...
    "YawRate",0,"SteeringAngle",0,"Valid",definition.Valid);
end
