function result=runRoadsenseScenarioSensorSourceDemo(showFigures)
%RUNROADSENSESCENARIOSENSORSOURCEDEMO Generate five sensor snapshots.
arguments
    showFigures (1,1) logical = true
end
visibility="off"; if showFigures; visibility="on"; end
times=[7 8 7 12 7];
names=["Village","Urban junction","Highway merge","Dense market","Cattle crossing"];
summaryRows=cell(5,1); dropoutRows=cell(5,1);
cameraFigure=figure("Name","Roadsense synthetic camera snapshots", ...
    "Color","white","Visible",visibility,"Position",[80 70 1450 820]);
cameraLayout=tiledlayout(cameraFigure,2,3,"TileSpacing","compact","Padding","loose");
cameraLayout.OuterPosition=[0 0 1 0.94];
annotation(cameraFigure,"textbox",[0.2 0.95 0.6 0.04], ...
    "String","Roadsense | Scenario camera measurements","EdgeColor","none", ...
    "HorizontalAlignment","center","FontSize",16,"FontWeight","bold", ...
    "Color",[0.08 0.08 0.08]);
geometryFigure=figure("Name","Roadsense LiDAR and radar geometry", ...
    "Color","white","Visible",visibility,"Position",[100 90 1450 820]);
geometryLayout=tiledlayout(geometryFigure,2,3,"TileSpacing","compact","Padding","loose");
geometryLayout.OuterPosition=[0 0 1 0.94];
annotation(geometryFigure,"textbox",[0.2 0.95 0.6 0.04], ...
    "String","Roadsense | LiDAR point clouds and radar detections","EdgeColor","none", ...
    "HorizontalAlignment","center","FontSize",16,"FontWeight","bold", ...
    "Color",[0.08 0.08 0.08]);

for id=1:5
    data=createSyntheticRoadsenseScenarioSensorInputs(id,times(id));
    camera=RoadsenseScenarioCameraSystem;
    [image,cameraValid,cameraCount,cameraOccluded,cameraDropout]=camera( ...
        data.CurrentTime,data.EgoState,data.TruthActors,data.ScenarioDefinition,data.ScenarioStatus);
    lidar=RoadsenseScenarioLidarSystem;
    [points,intensity,lidarCount,~,lidarValid,lidarActors,lidarOccluded,lidarDropout]=lidar( ...
        data.CurrentTime,data.EgoState,data.TruthActors,data.ScenarioDefinition,data.ScenarioStatus);
    radar=RoadsenseScenarioRadarSystem;
    [radarPositions,~,~,~,radarScores,radarCount,~,radarValid,~,radarOccluded,radarDropout]=radar( ...
        data.CurrentTime,data.EgoState,data.TruthActors,data.ScenarioDefinition,data.ScenarioStatus);

    ax=nexttile(cameraLayout,id); imshow(image,"Parent",ax);
    title(ax,sprintf("%d. %s | camera actors %d",id,names(id),cameraCount), ...
        "Color",[0.08 0.08 0.08],"FontWeight","bold");
    ax=nexttile(geometryLayout,id); hold(ax,"on"); grid(ax,"on");
    cloud=points(1:double(lidarCount),:); sample=1:5:size(cloud,1);
    scatter(ax,cloud(sample,1),cloud(sample,2),7,double(intensity(sample)), ...
        "filled","MarkerFaceAlpha",0.35,"DisplayName","LiDAR");
    if radarCount>0
        scatter(ax,radarPositions(1:double(radarCount),1), ...
            radarPositions(1:double(radarCount),2),70, ...
            radarScores(1:double(radarCount)),"d","filled","MarkerEdgeColor",[0.4 0 0.5], ...
            "DisplayName","Radar");
    end
    styleAxes(ax); axis(ax,"equal"); xlim(ax,[-12 72]); ylim(ax,[-22 22]);
    title(ax,sprintf("%d. %s | %d points, %d radar",id,names(id),lidarCount,radarCount), ...
        "Color",[0.08 0.08 0.08],"FontWeight","bold");
    xlabel(ax,"Ego forward (m)"); ylabel(ax,"Ego left (m)");

    summaryRows{id}=table(id,names(id),times(id),cameraCount,lidarCount,lidarActors, ...
        radarCount,cameraOccluded,lidarOccluded,radarOccluded, ...
        cameraValid,lidarValid,radarValid, ...
        'VariableNames',{'ScenarioID','Name','SnapshotTime_s','CameraActors', ...
        'LidarPoints','LidarActors','RadarDetections','CameraOccluded','LidarOccluded', ...
        'RadarOccluded','CameraValid','LidarValid','RadarValid'});
    scanTimes=(0:0.05:double(data.ScenarioStatus.Duration)).';
    cameraFlags=false(size(scanTimes)); lidarFlags=false(size(scanTimes)); radarFlags=false(size(scanTimes));
    for k=1:numel(scanTimes)
        [cameraFlags(k),lidarFlags(k),radarFlags(k)]= ...
            RoadsenseScenarioSensorUtilities.dropoutSchedule(id,scanTimes(k));
    end
    dropoutRows{id}=table(id,sum(cameraFlags)*0.05,sum(lidarFlags)*0.05, ...
        sum(radarFlags)*0.05,'VariableNames',{'ScenarioID','CameraDropout_s', ...
        'LidarDropout_s','RadarDropout_s'});
end
axis(nexttile(cameraLayout,6),"off");
text(nexttile(cameraLayout,6),0.05,0.92,{"Synthetic but deterministic RGB", ...
    "Perspective road envelope","Class-coloured actor silhouettes", ...
    "Occlusion and scheduled dropout","Damaged-surface visual evidence"}, ...
    "Color",[0.08 0.08 0.08],"FontSize",11,"VerticalAlignment","top");
axis(nexttile(geometryLayout,6),"off");
text(nexttile(geometryLayout,6),0.05,0.92,{"LiDAR: ground + cuboid surfaces", ...
    "Colour: normalized reflectivity","Diamonds: noisy radar detections", ...
    "All coordinates are ego-frame"},"Color",[0.08 0.08 0.08], ...
    "FontSize",11,"VerticalAlignment","top");
result=struct("Summary",vertcat(summaryRows{:}),"DropoutSchedule",vertcat(dropoutRows{:}), ...
    "CameraFigure",cameraFigure,"GeometryFigure",geometryFigure);
end

function styleAxes(ax)
ax.Color=[0.98 0.98 0.98]; ax.XColor=[0.15 0.15 0.15]; ax.YColor=[0.15 0.15 0.15];
ax.GridColor=[0.72 0.72 0.72]; ax.GridAlpha=0.45; ax.FontName="Arial"; ax.FontSize=9;
end
