function modelPath=createRoadsenseLocalPlannerModel()
%CREATEROADSENSELOCALPLANNERMODEL Generate the adaptive local-planner model.

componentDir=fileparts(mfilename("fullpath"));
root=fileparts(fileparts(componentDir));
modelName="Roadsense_LocalPlanner";
modelPath=fullfile(componentDir,modelName+".slx");
addpath(fullfile(root,"Models","SharedData")); addpath(componentDir); addpath(fullfile(root,"Data"));
createRoadsenseDataDictionary(fullfile(root,"Data","Roadsense_Data.sldd"));
if bdIsLoaded(modelName); close_system(modelName,0); end
if isfile(modelPath); delete(modelPath); end
new_system(modelName,"Model"); cleanup=onCleanup(@() closeIfLoaded(modelName));
set_param(modelName,"DataDictionary","Roadsense_Data.sldd", ...
    "SolverType","Fixed-step","Solver","FixedStepDiscrete", ...
    "FixedStep","RsTsBase","StopTime","1.0","SignalLogging","on");

inputNames=["EgoState","SemanticGrid","FusedTracks","Predictions", ...
    "BehaviourCommand","ReferencePath"];
inputTypes=["Bus: RsEgoStateBus","Bus: RsSemanticGridBus", ...
    "Bus: RsFusedTrackListBus","Bus: RsMotionPredictionListBus", ...
    "Bus: RsBehaviourCommandBus","Bus: RsReferencePathBus"];
for index=1:6
    y=105+(index-1)*70;
    add_block("simulink/Ports & Subsystems/In1",modelName+"/"+inputNames(index), ...
        "Position",[25 y 55 y+20],"Port",string(index), ...
        "OutDataTypeStr",inputTypes(index),"PortDimensions","1", ...
        "SampleTime","RsTsPlanning");
end

planner=modelName+"/Trajectory Sampling and Safety Filter";
add_block("simulink/User-Defined Functions/MATLAB System",planner, ...
    "Position",[165 80 455 515]);
set_param(planner,"System","RoadsenseLocalPlannerSystem", ...
    "MaxPlanPoints","double(RsMaxPlanPoints)", ...
    "MaxReferencePoints","double(RsMaxReferencePoints)", ...
    "MaxTracks","double(RsMaxTracks)", ...
    "MaxModes","double(RsMaxPredictionModes)", ...
    "PredictionSteps","double(RsPredictionSteps)", ...
    "GridRows","double(RsGridRows)","GridCols","double(RsGridCols)", ...
    "PlanStep","RsPlanStep","PlanHorizon","RsPlanHorizon", ...
    "LateralTransitionDistance","RsPlannerLateralTransitionDistance", ...
    "LateralOffsets","RsPlannerLateralOffsets", ...
    "SpeedScales","RsPlannerSpeedScales","Wheelbase","RsPlannerWheelbase", ...
    "VehicleLength","RsPlannerVehicleLength","VehicleWidth","RsPlannerVehicleWidth", ...
    "MaximumCurvature","RsPlannerMaximumCurvature", ...
    "MaximumJerk","RsPlannerMaximumJerk","HardOccupancy","RsPlannerHardOccupancy", ...
    "CollisionProbability","RsPlannerCollisionProbability", ...
    "PredictionSigma","RsPlannerPredictionSigma", ...
    "MaximumLongitudinalInflation","RsPlannerMaximumLongitudinalInflation", ...
    "MaximumLateralInflation","RsPlannerMaximumLateralInflation", ...
    "LateralClearanceRatio","RsPlannerLateralClearanceRatio", ...
    "MaximumLateralClearance","RsPlannerMaximumLateralClearance", ...
    "Deadline","RsPlannerDeadline");
for index=1:6
    line=add_line(modelName,inputNames(index)+"/1", ...
        "Trajectory Sampling and Safety Filter/"+index,"autorouting","on");
    set_param(line,"Name",inputNames(index));
end

add_block("simulink/Signal Attributes/Data Type Conversion",modelName+"/Planner Code Enum", ...
    "Position",[535 340 625 370],"OutDataTypeStr","Enum: RoadsenseTypes.PlannerCode");
add_block("simulink/Signal Attributes/Data Type Conversion",modelName+"/Behaviour Enum", ...
    "Position",[535 385 625 415],"OutDataTypeStr","Enum: RoadsenseTypes.BehaviourMode");
add_line(modelName,"Trajectory Sampling and Safety Filter/19","Planner Code Enum/1","autorouting","on");
add_line(modelName,"Trajectory Sampling and Safety Filter/20","Behaviour Enum/1","autorouting","on");

add_block("simulink/Signal Routing/Bus Creator",modelName+"/Local Plan Bus", ...
    "Position",[700 55 710 365],"Inputs","16", ...
    "OutDataTypeStr","Bus: RsLocalPlanBus");
planNames=["Timestamp","PlanID","Count","TimeFromStart","Positions","Yaws", ...
    "Speeds","Accelerations","Curvatures","SteeringAngles","TotalCost", ...
    "MinimumClearance","CandidateCount","FeasibleCount","EmergencyFallback","Valid"];
for port=1:16
    line=add_line(modelName,"Trajectory Sampling and Safety Filter/"+port, ...
        "Local Plan Bus/"+port,"autorouting","on");
    set_param(line,"Name",planNames(port));
end

add_block("simulink/Signal Routing/Bus Creator",modelName+"/Planner Status Bus", ...
    "Position",[700 390 710 585],"Inputs","10", ...
    "OutDataTypeStr","Bus: RsPlannerStatusBus");
statusSources=["Trajectory Sampling and Safety Filter/17", ...
    "Trajectory Sampling and Safety Filter/18","Planner Code Enum/1", ...
    "Behaviour Enum/1","Trajectory Sampling and Safety Filter/21", ...
    "Trajectory Sampling and Safety Filter/22","Trajectory Sampling and Safety Filter/23", ...
    "Trajectory Sampling and Safety Filter/24","Trajectory Sampling and Safety Filter/25", ...
    "Trajectory Sampling and Safety Filter/26"];
statusNames=["Timestamp","PlanID","Code","Behaviour","CandidateCount", ...
    "FeasibleCount","ExecutionTime","Deadline","ReplanRequested","EmergencyRequested"];
for port=1:10
    line=add_line(modelName,statusSources(port),"Planner Status Bus/"+port,"autorouting","on");
    set_param(line,"Name",statusNames(port));
end

add_block("simulink/Ports & Subsystems/Out1",modelName+"/LocalPlan", ...
    "Position",[805 190 835 210],"OutDataTypeStr","Bus: RsLocalPlanBus");
add_block("simulink/Ports & Subsystems/Out1",modelName+"/PlannerStatus", ...
    "Position",[805 475 835 495],"Port","2", ...
    "OutDataTypeStr","Bus: RsPlannerStatusBus");
add_line(modelName,"Local Plan Bus/1","LocalPlan/1","autorouting","on");
add_line(modelName,"Planner Status Bus/1","PlannerStatus/1","autorouting","on");

annotation=Simulink.Annotation(modelName,"Roadsense Adaptive Local Planner"+newline+ ...
    "route-relative candidate sampling -> static and multimodal dynamic safety -> feasibility and cost"+newline+ ...
    "always emits a bounded minimum-risk braking fallback when no nominal candidate survives");
annotation.Position=[160 15 780 65];
save_system(modelName,modelPath); clear cleanup; close_system(modelName,0);
fprintf("Generated %s\n",modelPath);
end

function closeIfLoaded(modelName)
if bdIsLoaded(modelName); close_system(modelName,0); end
end
