function modelPath=createRoadsenseRoadRunnerIntegrationModel()
%CREATEROADSENSEROADRUNNERINTEGRATIONMODEL Build the RoadRunner actor model.
componentDir=fileparts(mfilename("fullpath")); root=fileparts(fileparts(componentDir));
modelName="Roadsense_RoadRunnerIntegration";
modelPath=fullfile(componentDir,modelName+".slx");
addpath(genpath(fullfile(root,"Models"))); addpath(fullfile(root,"Data"));
createRoadsenseDataDictionary(fullfile(root,"Data","Roadsense_Data.sldd"));
Simulink.ActorSimulation.load('BusActorPose');
ensureHarness(root);
if bdIsLoaded(modelName); close_system(modelName,0); end
if isfile(modelPath); delete(modelPath); end
new_system(modelName,"Model"); cleanup=onCleanup(@() closeIfLoaded(modelName));
set_param(modelName,"DataDictionary","Roadsense_Data.sldd", ...
    "SolverType","Fixed-step","Solver","FixedStepDiscrete", ...
    "FixedStep","RsTsBase","StopTime","inf","SignalLogging","on", ...
    "PreLoadFcn","");
modelWorkspace=get_param(modelName,"ModelWorkspace");
assignin(modelWorkspace,"RsRoadRunnerScenarioID",uint8(1));

% RoadRunner requires this interface block at the top level of every
% Simulink actor behavior. The Reader/Writer pair exchanges messages with
% the actor to which this model is attached.
load_system("roadrunnerscenario");
add_block("roadrunnerscenario/RoadRunner Scenario", ...
    modelName+"/RoadRunner Scenario","Position",[70 55 250 125], ...
    "BackgroundColor","[0.82 0.72 0.95]");
readerSource=sprintf('roadrunnerscenario/RoadRunner Scenario\nReader');
writerSource=sprintf('roadrunnerscenario/RoadRunner Scenario\nWriter');
add_block(readerSource,modelName+"/Read Self Actor Pose", ...
    "Position",[70 235 250 305],"TopicCategory","Actor", ...
    "ActorCategory","All Types", ...
    "TopicType","Actor Pose (Driving Scenario compatible)", ...
    "Filter","Self","SampleTime","RsTsControl", ...
    "BackgroundColor","[0.82 0.72 0.95]");
add_block(writerSource,modelName+"/Write Planned Ego Pose", ...
    "Position",[1490 235 1690 305],"TopicCategory","Actor", ...
    "ActorCategory","All Types", ...
    "TopicType","Actor Pose (Driving Scenario compatible)", ...
    "BackgroundColor","[0.82 0.72 0.95]");

load_system("simulink");
receiveSource=sprintf('simulink/Messages\n& Events/Receive');
sendSource=sprintf('simulink/Messages\n& Events/Send');
add_block(receiveSource,modelName+"/Receive Actor Message", ...
    "Position",[315 235 365 305],"SampleTime","RsTsControl");
add_block(sendSource,modelName+"/Send Actor Message", ...
    "Position",[1385 235 1435 305]);
add_block("simulink/Signal Routing/Bus Selector",modelName+"/Actor ID", ...
    "Position",[430 230 465 285],"OutputSignals","ActorID");

add_block("simulink/Sources/Constant",modelName+"/Selected Indian Road Stage", ...
    "Position",[75 455 250 495],"Value","RsRoadRunnerScenarioID", ...
    "OutDataTypeStr","uint8","SampleTime","RsTsScenario", ...
    "BackgroundColor","[0.72 0.87 1.00]");
add_block("simulink/Sources/Constant",modelName+"/No Manual Reset", ...
    "Position",[75 545 250 585],"Value","false", ...
    "OutDataTypeStr","boolean","SampleTime","RsTsControl", ...
    "BackgroundColor","[0.72 0.87 1.00]");
add_block("simulink/Ports & Subsystems/Model", ...
    modelName+"/Complete Roadsense Closed-Loop Harness", ...
    "Position",[430 430 825 645], ...
    "ModelName","Roadsense_ScenarioClosedLoopHarness", ...
    "SimulationMode","Normal","BackgroundColor","[0.73 0.91 0.75]", ...
    "FontWeight","bold","FontSize","12");

add_block("simulink/Signal Routing/Bus Selector",modelName+"/Ego Pose Fields", ...
    "Position",[900 385 945 610], ...
    "OutputSignals","Position,Velocity,Roll,Pitch,Yaw,YawRate");
add_block("simulink/Math Operations/Reshape",modelName+"/Position Row", ...
    "Position",[1015 390 1090 420],"OutputDimensionality","Customize", ...
    "OutputDimensions","[1 3]");
add_block("simulink/Math Operations/Reshape",modelName+"/Velocity Row", ...
    "Position",[1015 445 1090 475],"OutputDimensionality","Customize", ...
    "OutputDimensions","[1 3]");
add_block("simulink/Sources/Constant",modelName+"/Zero Angular XY", ...
    "Position",[1015 600 1090 630],"Value","[0;0]", ...
    "OutDataTypeStr","double");
add_block("simulink/Signal Routing/Mux",modelName+"/Angular Velocity Vector", ...
    "Position",[1150 565 1155 635],"Inputs","2");
add_block("simulink/Math Operations/Reshape",modelName+"/Angular Velocity Row", ...
    "Position",[1205 585 1290 615],"OutputDimensionality","Customize", ...
    "OutputDimensions","[1 3]");
add_block("simulink/Signal Routing/Bus Creator",modelName+"/RoadRunner Actor Pose Bus", ...
    "Position",[1280 350 1290 555],"Inputs","7", ...
    "OutDataTypeStr","Bus: BusActorPose","NonVirtualBus","on", ...
    "BackgroundColor","[0.98 0.93 0.72]");

wire(modelName,"Read Self Actor Pose/1","Receive Actor Message/1","");
wire(modelName,"Receive Actor Message/1","Actor ID/1","");
wire(modelName,"Selected Indian Road Stage/1", ...
    "Complete Roadsense Closed-Loop Harness/1","");
wire(modelName,"No Manual Reset/1", ...
    "Complete Roadsense Closed-Loop Harness/2","");
wire(modelName,"Complete Roadsense Closed-Loop Harness/1","Ego Pose Fields/1","");
wire(modelName,"Ego Pose Fields/1","Position Row/1","");
wire(modelName,"Ego Pose Fields/2","Velocity Row/1","");
wire(modelName,"Zero Angular XY/1","Angular Velocity Vector/1","");
wire(modelName,"Ego Pose Fields/6","Angular Velocity Vector/2","");
wire(modelName,"Angular Velocity Vector/1","Angular Velocity Row/1","");

poseSources=["Actor ID/1","Position Row/1","Velocity Row/1", ...
    "Ego Pose Fields/3","Ego Pose Fields/4","Ego Pose Fields/5", ...
    "Angular Velocity Row/1"];
for index=1:numel(poseSources)
    wire(modelName,poseSources(index),"RoadRunner Actor Pose Bus/"+index,"");
end
wire(modelName,"RoadRunner Actor Pose Bus/1","Send Actor Message/1","");
wire(modelName,"Send Actor Message/1","Write Planned Ego Pose/1","");

% Terminate logged evidence buses immediately beside their model ports so
% the visual pose path remains uncluttered.
evidenceBlocks=["Semantic Map Evidence","Track Evidence","Local Plan Evidence", ...
    "Safety Evidence","Integration Evidence","Sensor Evidence", ...
    "Acceptance Evidence"];
evidenceY=[476 499 522 568 591 614 637];
for index=1:numel(evidenceBlocks)
    add_block("simulink/Sinks/Terminator",modelName+"/"+evidenceBlocks(index), ...
        "Position",[850 evidenceY(index)-8 870 evidenceY(index)+8], ...
        "ShowName","off");
end
evidencePorts=[2 3 4 6 7 8 9];
for index=1:numel(evidencePorts)
    wire(modelName,"Complete Roadsense Closed-Loop Harness/"+evidencePorts(index), ...
        evidenceBlocks(index)+"/1","");
end

title=Simulink.Annotation(modelName,"ROADSENSE  |  ROADRUNNER 3D CO-SIMULATION");
title.Position=[520 30 1230 65]; title.FontSize=17; title.FontWeight="bold";
subtitle=Simulink.Annotation(modelName,sprintf([ ...
    'RoadRunner actor message -> full Simulink autonomy stack -> planned ego pose -> RoadRunner 3D vehicle\n' ...
    'RsRoadRunnerScenarioID selects one of the five official Indian-road stages']));
subtitle.Position=[475 80 1320 135]; subtitle.FontSize=11;
zone1=Simulink.Annotation(modelName,"ROADRUNNER MESSAGE INTERFACE");
zone1.Position=[65 180 470 210]; zone1.FontWeight="bold";
zone2=Simulink.Annotation(modelName,"SIMULINK PERCEPTION + PLANNING + CONTROL");
zone2.Position=[395 355 990 385]; zone2.FontWeight="bold";
zone3=Simulink.Annotation(modelName,"3D POSE PUBLICATION");
zone3.Position=[1210 180 1690 210]; zone3.FontWeight="bold";
set_param(modelName,"Location",[35 35 1770 1000]);
applyRoadsenseModelStyle(modelName);
save_system(modelName,modelPath); clear cleanup; close_system(modelName,0);
close_system("roadrunnerscenario",0); close_system("simulink",0);
fprintf("Generated %s\n",modelPath);
end

function ensureHarness(root)
harnessPath=fullfile(root,"Models","ScenarioClosedLoopHarness", ...
    "Roadsense_ScenarioClosedLoopHarness.slx");
if ~isfile(harnessPath); createRoadsenseScenarioClosedLoopHarnessModel(); end
end

function wire(system,source,destination,name)
line=add_line(system,source,destination,"autorouting","on");
if strlength(name)>0; set_param(line,"Name",name); end
end

function closeIfLoaded(modelName)
if bdIsLoaded(modelName); close_system(modelName,0); end
end
