function path=writeRoadsenseTuningReport(comparison,recommended,options,wallTime)
%WRITEROADSENSETUNINGREPORT Write a concise auditable Markdown decision log.
path=fullfile(options.OutputDirectory,"tuning_report.md");
lines=["# Roadsense scenario tuning report";""; ...
    "Inference backend: `"+options.InferenceMode+"`"; ...
    "Scenarios: "+strjoin(string(options.ScenarioIDs),", "); ...
    "Suite wall time: "+compose("%.1f s",wallTime); ...
    "Recommended profile: **"+recommended+"**";""; ...
    "| Profile | Collision-free | Completed | Passed | Ready % | Worst latency ms | Objective |"; ...
    "|---|---:|---:|---:|---:|---:|---:|"];
for index=1:height(comparison)
    row=comparison(index,:);
    lines(end+1)=sprintf("| %s | %d/%d | %d/%d | %d/%d | %.1f | %.2f | %.1f |", ...
        row.Profile,row.CollisionFree,row.Scenarios,row.Completed,row.Scenarios, ...
        row.Passed,row.Scenarios,row.MeanReadyPercent,row.WorstLatencyMs,row.Objective); %#ok<AGROW>
end
lines=[lines;"";"The ranking is safety-first: simulation failures, collisions, non-completion, and missed goals dominate comfort or latency terms."; ...
    "Evaluator thresholds are never modified by a tuning profile."];
writelines(lines,path);
end
