function inputs=createSyntheticRoadsenseIntegrationInputs()
%CREATESYNTHETICROADSENSEINTEGRATIONINPUTS Create valid monitor bus structs.
[ego,semanticGrid,fusedTracks,behaviour,plannerStatus,trackingStatus, ...
    dynamicsStatus,nominalControl]=createSyntheticRoadsenseSafetyInputs("normal");
[imageSemantic,lidarGrid,~,predictions]=createSyntheticRoadsenseMapInputs();
[~,localPlan,~]=createSyntheticRoadsenseControllerInputs("aligned");
[~,~,~,routeContext]=createSyntheticRoadsenseBehaviourInputs("cruise");

timestamp=ego.Timestamp;
timeStamped={imageSemantic,lidarGrid,fusedTracks,predictions,semanticGrid, ...
    behaviour,localPlan,plannerStatus,nominalControl,trackingStatus, ...
    dynamicsStatus,routeContext};
for index=1:numel(timeStamped)
    timeStamped{index}.Timestamp=timestamp;
end
[imageSemantic,lidarGrid,fusedTracks,predictions,semanticGrid,behaviour, ...
    localPlan,plannerStatus,nominalControl,trackingStatus,dynamicsStatus, ...
    routeContext]=timeStamped{:};

safeControl=nominalControl;
safetyStatus=struct("Timestamp",timestamp,"SequenceID",uint32(1), ...
    "State",RoadsenseTypes.SafetyState.Normal,"ReasonMask",uint16(0), ...
    "MinimumTTC",single(inf),"NearestDistance",single(inf), ...
    "MaximumInputAge",single(0),"CrossTrackError",single(0), ...
    "SideslipAngle",single(0),"FrictionUtilization",single(0.2), ...
    "OverrideActive",false,"EmergencyLatched",false, ...
    "SafeToDrive",true,"Valid",true);

inputs={ego,imageSemantic,lidarGrid,fusedTracks,predictions,semanticGrid, ...
    behaviour,localPlan,plannerStatus,nominalControl,trackingStatus, ...
    safetyStatus,safeControl,dynamicsStatus,routeContext};
end
