function modelPath=createRoadsenseScenarioClosedLoopHarnessModel()
%CREATEROADSENSESCENARIOCLOSEDLOOPHARNESS Build the full scenario validation harness.
componentDir=fileparts(mfilename("fullpath")); root=fileparts(fileparts(componentDir));
modelName="Roadsense_ScenarioClosedLoopHarness";
modelPath=fullfile(componentDir,modelName+".slx");
addpath(genpath(fullfile(root,"Models"))); addpath(fullfile(root,"Data"));
createRoadsenseDataDictionary(fullfile(root,"Data","Roadsense_Data.sldd"));
ensureHarnessModels(root);
if bdIsLoaded(modelName); close_system(modelName,0); end
if isfile(modelPath); delete(modelPath); end
new_system(modelName,"Model"); cleanup=onCleanup(@() closeIfLoaded(modelName));
set_param(modelName,"DataDictionary","Roadsense_Data.sldd", ...
    "SolverType","Fixed-step","Solver","FixedStepDiscrete", ...
    "FixedStep","RsTsBase","StopTime","25", ...
    "SignalLogging","on","ScreenColor","white","ZoomFactor","FitSystem");

add_block("simulink/Ports & Subsystems/In1",modelName+"/ScenarioSelect", ...
    "Position",[40 255 70 275],"Port","1","OutDataTypeStr","uint8", ...
    "SampleTime","RsTsScenario","BackgroundColor","lightBlue");
add_block("simulink/Ports & Subsystems/In1",modelName+"/ManualReset", ...
    "Position",[40 335 70 355],"Port","2","OutDataTypeStr","boolean", ...
    "SampleTime","RsTsControl","BackgroundColor","lightBlue");
add_block("simulink/Sources/Digital Clock",modelName+"/Scenario Clock", ...
    "Position",[40 175 90 205],"SampleTime","RsTsBase", ...
    "BackgroundColor","lightBlue");

environment=modelName+"/Simulated Indian Road Environment";
addEnvironmentSubsystem(environment,[220 125 655 585]);
stack=modelName+"/Roadsense Autonomous Driving Stack";
add_block("simulink/Ports & Subsystems/Model",stack,"Position",[850 125 1290 585], ...
    "ModelName","Roadsense_ClosedLoopIntegration","SimulationMode","Normal", ...
    "BackgroundColor","[0.73 0.91 0.75]","FontWeight","bold","FontSize","12");
evaluation=modelName+"/Truth-Isolated Acceptance Evaluation";
addEvaluationSubsystem(evaluation,[850 750 1290 1125]);
add_block("simulink/Discrete/Unit Delay",modelName+"/One Control Tick Ego Feedback Delay", ...
    "Position",[710 315 810 350],"SampleTime","RsTsControl", ...
    "InitialCondition","0","BackgroundColor","[0.80 0.90 1.00]");

wire(modelName,"Scenario Clock/1","Simulated Indian Road Environment/1","CurrentTime");
wire(modelName,"ScenarioSelect/1","Simulated Indian Road Environment/2","ScenarioSelect");
wire(modelName,"Roadsense Autonomous Driving Stack/1", ...
    "One Control Tick Ego Feedback Delay/1","EgoState");
wire(modelName,"One Control Tick Ego Feedback Delay/1", ...
    "Simulated Indian Road Environment/3","DelayedEgoFeedback");
wire(modelName,"ManualReset/1","Simulated Indian Road Environment/4","ManualReset");
for index=1:8
    wire(modelName,"Simulated Indian Road Environment/"+index, ...
        "Roadsense Autonomous Driving Stack/"+index,"");
end

% Only planner-visible sensor products enter the stack. Ground truth has a
% physically separate route into the metric evaluator below the boundary.
stackToEvaluation=[1 4 5 6 7 8 9 10];
for index=1:numel(stackToEvaluation)
    wire(modelName,"Roadsense Autonomous Driving Stack/"+stackToEvaluation(index), ...
        "Truth-Isolated Acceptance Evaluation/"+index,"");
end
for index=1:3
    wire(modelName,"Simulated Indian Road Environment/"+(8+index), ...
        "Truth-Isolated Acceptance Evaluation/"+(8+index),"");
end
stackPorts=get_param(stack,"PortHandles");
diagnosticPorts=[8 9 10 11];
diagnosticNames=["PlannerStatus","TrackingStatus","DynamicsStatus","BehaviourCommand"];
for index=1:numel(diagnosticPorts)
    set_param(stackPorts.Outport(diagnosticPorts(index)),"DataLogging","on", ...
        "DataLoggingNameMode","Custom","DataLoggingName",diagnosticNames(index));
end

outputNames=["EgoState","SemanticGrid","FusedTracks","LocalPlan", ...
    "SafeVehicleControl","SafetyStatus","IntegrationStatus", ...
    "SensorStatus","EvaluationStatus"];
outputTypes=["Bus: RsEgoStateBus","Bus: RsSemanticGridBus", ...
    "Bus: RsFusedTrackListBus","Bus: RsLocalPlanBus", ...
    "Bus: RsVehicleControlBus","Bus: RsSafetyStatusBus", ...
    "Bus: RsIntegrationStatusBus","Bus: RsScenarioSensorStatusBus", ...
    "Bus: RsScenarioEvaluationBus"];
outputSources=["Roadsense Autonomous Driving Stack/1", ...
    "Roadsense Autonomous Driving Stack/2","Roadsense Autonomous Driving Stack/3", ...
    "Roadsense Autonomous Driving Stack/4","Roadsense Autonomous Driving Stack/5", ...
    "Roadsense Autonomous Driving Stack/6","Roadsense Autonomous Driving Stack/7", ...
    "Simulated Indian Road Environment/11","Truth-Isolated Acceptance Evaluation/1"];
for index=1:numel(outputNames)
    y=135+(index-1)*105;
    add_block("simulink/Ports & Subsystems/Out1",modelName+"/"+outputNames(index), ...
        "Position",[1510 y 1540 y+20],"Port",string(index), ...
        "OutDataTypeStr",outputTypes(index));
    wire(modelName,outputSources(index),outputNames(index)+"/1","");
    if ismember(index,[1 4 5 6 7 8 9])
        portHandles=get_param(modelName+"/"+outputNames(index),"PortHandles");
        lineHandle=get_param(portHandles.Inport,"Line");
        sourcePort=get_param(lineHandle,"SrcPortHandle");
        set_param(sourcePort,"DataLogging","on", ...
            "DataLoggingNameMode","Custom","DataLoggingName",outputNames(index));
    end
end

title=Simulink.Annotation(modelName,"ROADSENSE  |  SCENARIO CLOSED-LOOP VALIDATION HARNESS");
title.Position=[360 20 1180 55]; title.FontSize=17; title.FontWeight="bold";
subtitle=Simulink.Annotation(modelName,sprintf([ ...
    'Five Indian-road scenarios  ->  camera + LiDAR + radar  ->  complete autonomy stack\n' ...
    'Ego-state feedback closes the loop; ground truth is isolated below the planning boundary']));
subtitle.Position=[390 65 1210 112]; subtitle.FontSize=11;
boundary=Simulink.Annotation(modelName,sprintf([ ...
    'TRUTH BOUNDARY\nGround truth is used only for sensor synthesis and independent scoring.\n' ...
    'The autonomous stack receives sensor measurements, map/route context and ego feedback.']));
boundary.Position=[235 650 700 750]; boundary.FontSize=10;
legendNote=Simulink.Annotation(modelName,sprintf([ ...
    'BLUE  simulated environment\nGREEN  autonomous driving stack\nGREY  independent evaluation']));
legendNote.Position=[1350 1010 1570 1105]; legendNote.FontSize=9;
set_param(modelName,"Location",[45 30 1660 970]);
applyRoadsenseModelStyle(modelName);
save_system(modelName,modelPath); clear cleanup; close_system(modelName,0);
fprintf("Generated %s\n",modelPath);
end

function addEnvironmentSubsystem(path,position)
add_block("simulink/Ports & Subsystems/Subsystem",path,"Position",position, ...
    "BackgroundColor","[0.72 0.87 1.00]","FontWeight","bold","FontSize","12");
set_param(path,"ContentPreviewEnabled","off"); Simulink.SubSystem.deleteContents(path);
inputNames=["CurrentTime","ScenarioSelect","EgoFeedback","ManualReset"];
inputTypes=["double","uint8","Bus: RsEgoStateBus","boolean"];
inputTimes=["RsTsBase","RsTsScenario","RsTsControl","RsTsControl"];
for index=1:4
    y=65+(index-1)*115;
    add_block("simulink/Ports & Subsystems/In1",path+"/"+inputNames(index), ...
        "Position",[20 y 50 y+20],"Port",string(index), ...
        "OutDataTypeStr",inputTypes(index),"SampleTime",inputTimes(index));
end
addRate(path,"Time base to scenario rate","RsTsScenario",[105 55 220 85]);
addRate(path,"Ego 50 to 10 Hz","RsTsScenario",[105 275 220 305]);
wire(path,"CurrentTime/1","Time base to scenario rate/1","ScenarioTime");
wire(path,"EgoFeedback/1","Ego 50 to 10 Hz/1","EgoAtSensorRate");

library=path+"/Indian Road Scenario Library";
add_block("simulink/Ports & Subsystems/Model",library,"Position",[310 45 565 155], ...
    "ModelName","Roadsense_ScenarioLibrary","SimulationMode","Normal", ...
    "BackgroundColor","[0.74 0.85 1.00]","FontWeight","bold");
source=path+"/Camera LiDAR Radar Source";
add_block("simulink/Ports & Subsystems/Model",source,"Position",[690 45 970 255], ...
    "ModelName","Roadsense_ScenarioSensorSource","SimulationMode","Normal", ...
    "BackgroundColor","[0.74 0.85 1.00]","FontWeight","bold");
bridge=path+"/One-Tick Sensor Latency and Radar Rate Bridge";
addSensorBridgeSubsystem(bridge,[1080 35 1380 300]);
adapters=path+"/Scenario-to-Stack Adapters";
add_block("simulink/Ports & Subsystems/Model",adapters,"Position",[1510 40 1795 420], ...
    "ModelName","Roadsense_ScenarioAdapters","SimulationMode","Normal", ...
    "BackgroundColor","[0.79 0.89 1.00]","FontWeight","bold");

wire(path,"Time base to scenario rate/1","Indian Road Scenario Library/1","");
wire(path,"ScenarioSelect/1","Indian Road Scenario Library/2","");
wire(path,"Time base to scenario rate/1","Camera LiDAR Radar Source/1","");
wire(path,"Ego 50 to 10 Hz/1","Camera LiDAR Radar Source/2","");
wire(path,"Indian Road Scenario Library/2","Camera LiDAR Radar Source/3","");
wire(path,"Indian Road Scenario Library/1","Camera LiDAR Radar Source/4","");
wire(path,"Indian Road Scenario Library/3","Camera LiDAR Radar Source/5","");
for index=1:15
    wire(path,"Camera LiDAR Radar Source/"+index, ...
        "One-Tick Sensor Latency and Radar Rate Bridge/"+index,"");
end
wire(path,"CurrentTime/1","Scenario-to-Stack Adapters/1","");
for index=1:15
    wire(path,"One-Tick Sensor Latency and Radar Rate Bridge/"+index, ...
        "Scenario-to-Stack Adapters/"+(index+1),"");
end
wire(path,"EgoFeedback/1","Scenario-to-Stack Adapters/17","");
wire(path,"Indian Road Scenario Library/1","Scenario-to-Stack Adapters/18","");
wire(path,"ManualReset/1","Scenario-to-Stack Adapters/19","");

outputNames=["CameraFrame","LidarFrame","RadarObjects","RouteContext", ...
    "ReferencePath","InitialState","RoadCondition","Reset", ...
    "TruthActors","ScenarioStatus","SensorStatus"];
outputTypes=["Bus: RsCameraFrameBus","Bus: RsLidarFrameBus", ...
    "Bus: RsRadarObjectListBus","Bus: RsRouteContextBus", ...
    "Bus: RsReferencePathBus","Bus: RsEgoStateBus","Bus: RsRoadConditionBus", ...
    "boolean","Bus: RsScenarioActorListBus","Bus: RsScenarioStatusBus", ...
    "Bus: RsScenarioSensorStatusBus"];
outputSources=strings(1,11);
for index=1:8; outputSources(index)="Scenario-to-Stack Adapters/"+index; end
outputSources(9:11)=["Indian Road Scenario Library/2", ...
    "Indian Road Scenario Library/3","Camera LiDAR Radar Source/16"];
for index=1:11
    y=40+(index-1)*67;
    source=outputSources(index);
    if index<=8
        % The integration model exposes a 100 Hz parent contract and then
        % performs its own explicit task-rate transitions.  Normalize every
        % stack-bound environment bus to that base rate at this boundary.
        transition="Stack Base "+outputNames(index);
        addRate(path,transition,"RsTsBase",[1830 y-5 1930 y+25]);
        wire(path,source,transition+"/1","");
        source=transition+"/1";
    end
    add_block("simulink/Ports & Subsystems/Out1",path+"/"+outputNames(index), ...
        "Position",[1975 y 2005 y+20],"Port",string(index), ...
        "OutDataTypeStr",outputTypes(index));
    wire(path,source,outputNames(index)+"/1",outputNames(index));
end
note=Simulink.Annotation(path,sprintf([ ...
    'MEASUREMENT PATH:  scenario truth -> sensor physics -> 100 ms latency -> typed stack buses\n' ...
    'Radar measurements are transferred from 10 Hz source generation to the 20 Hz fusion task.']));
note.Position=[610 490 1440 565]; note.FontSize=10;
set_param(path,"Location",[70 50 1820 840]);
end

function addSensorBridgeSubsystem(path,position)
add_block("simulink/Ports & Subsystems/Subsystem",path,"Position",position, ...
    "BackgroundColor","[0.82 0.90 1.00]","FontWeight","bold");
set_param(path,"ContentPreviewEnabled","off"); Simulink.SubSystem.deleteContents(path);
names=["CameraImage","CameraValid","LidarPoints","LidarIntensity","LidarCount", ...
    "LidarOverflow","LidarValid","RadarPositions","RadarVelocities", ...
    "RadarPositionCovariances","RadarVelocityCovariances","RadarScores", ...
    "RadarCount","RadarOverflow","RadarValid"];
types=["uint8","boolean","single","single","uint32","boolean","boolean", ...
    "single","single","single","single","single","uint16","boolean","boolean"];
dims={"[480 640 3]","1","[120000 3]","[120000 1]","1","1","1", ...
    "[256 3]","[256 3]","[3 3 256]","[3 3 256]","[256 1]","1","1","1"};
for index=1:15
    y=25+(index-1)*48;
    add_block("simulink/Ports & Subsystems/In1",path+"/"+names(index), ...
        "Position",[15 y 45 y+20],"Port",string(index), ...
        "OutDataTypeStr",types(index),"PortDimensions",dims{index}, ...
        "SampleTime","RsTsScenario");
    delay=path+"/Delay "+names(index);
    add_block("simulink/Discrete/Unit Delay",delay,"Position",[120 y-5 215 y+25], ...
        "SampleTime","RsTsScenario","InitialCondition","0");
    if index>=8
        transfer=path+"/Radar 10 to 20 Hz "+names(index);
        addRate(path,"Radar 10 to 20 Hz "+names(index),"RsTsFusion",[280 y-5 400 y+25]);
        wire(path,names(index)+"/1","Delay "+names(index)+"/1","");
        wire(path,"Delay "+names(index)+"/1", ...
            "Radar 10 to 20 Hz "+names(index)+"/1","");
        source="Radar 10 to 20 Hz "+names(index)+"/1";
    else
        wire(path,names(index)+"/1","Delay "+names(index)+"/1","");
        source="Delay "+names(index)+"/1";
    end
    add_block("simulink/Ports & Subsystems/Out1",path+"/"+names(index)+"Out", ...
        "Position",[490 y 520 y+20],"Port",string(index), ...
        "OutDataTypeStr",types(index),"PortDimensions",dims{index});
    wire(path,source,names(index)+"Out/1",names(index));
end
note=Simulink.Annotation(path,sprintf([ ...
    'Explicit one-scenario-tick (100 ms) measurement latency\n' ...
    'Radar rate transition supplies deterministic 20 Hz fusion inputs']));
note.Position=[110 760 475 820]; note.FontSize=9;
set_param(path,"Location",[90 40 1120 850]);
end

function addEvaluationSubsystem(path,position)
add_block("simulink/Ports & Subsystems/Subsystem",path,"Position",position, ...
    "BackgroundColor","[0.88 0.88 0.88]","FontWeight","bold","FontSize","12");
set_param(path,"ContentPreviewEnabled","off"); Simulink.SubSystem.deleteContents(path);
inputNames=["EgoState","LocalPlan","SafeControl","SafetyStatus", ...
    "IntegrationStatus","PlannerStatus","TrackingStatus","DynamicsStatus", ...
    "TruthActors","ScenarioStatus","SensorStatus"];
inputTypes=["Bus: RsEgoStateBus","Bus: RsLocalPlanBus", ...
    "Bus: RsVehicleControlBus","Bus: RsSafetyStatusBus", ...
    "Bus: RsIntegrationStatusBus","Bus: RsPlannerStatusBus", ...
    "Bus: RsTrackingStatusBus","Bus: RsVehicleDynamicsStatusBus", ...
    "Bus: RsScenarioActorListBus","Bus: RsScenarioStatusBus", ...
    "Bus: RsScenarioSensorStatusBus"];
for index=1:11
    y=30+(index-1)*58;
    add_block("simulink/Ports & Subsystems/In1",path+"/"+inputNames(index), ...
        "Position",[20 y 50 y+20],"Port",string(index), ...
        "OutDataTypeStr",inputTypes(index));
end
algorithm=path+"/Metric Accumulator";
add_block("simulink/User-Defined Functions/MATLAB System",algorithm, ...
    "Position",[165 30 420 660],"BackgroundColor","[0.88 0.88 0.88]");
set_param(algorithm,"System","RoadsenseScenarioEvaluationSystem", ...
    "SimulateUsing","Interpreted execution", ...
    "RequiredClearance","RsScenarioMinimumClearance", ...
    "MaximumAllowedReplanLatency","RsScenarioMaximumReplanLatency", ...
    "MaximumAllowedPathSmoothness","RsScenarioMaximumPathCurvatureRMS", ...
    "MaximumAllowedJerk","RsScenarioMaximumJerk", ...
    "MaximumAllowedCrossTrackError","RsScenarioMaximumCrossTrackError", ...
    "MinimumReadyRatio","RsScenarioMinimumReadyRatio");
for index=1:11; wire(path,inputNames(index)+"/1","Metric Accumulator/"+index,""); end
add_block("simulink/Signal Routing/Bus Creator",path+"/Evaluation Bus", ...
    "Position",[525 35 535 655],"Inputs","18", ...
    "OutDataTypeStr","Bus: RsScenarioEvaluationBus");
metricNames=["Timestamp","ScenarioID","ElapsedTime","MinimumClearance", ...
    "Collision","GoalReached","ScenarioFinished","ReplanCount", ...
    "LastReplanLatency","MaximumReplanLatency","PathSmoothness","MaximumJerk", ...
    "MaximumCrossTrackError","SafetyInterventionCount","PipelineReadyRatio", ...
    "SensorDropoutMask","Pass","Valid"];
for index=1:18
    wire(path,"Metric Accumulator/"+index,"Evaluation Bus/"+index,metricNames(index));
end
add_block("simulink/Ports & Subsystems/Out1",path+"/EvaluationStatus", ...
    "Position",[650 335 680 355],"Port","1", ...
    "OutDataTypeStr","Bus: RsScenarioEvaluationBus");
wire(path,"Evaluation Bus/1","EvaluationStatus/1","EvaluationStatus");
set_param(path,"Location",[80 45 1210 820]);
end

function addRate(system,name,outSampleTime,position)
add_block("simulink/Signal Attributes/Rate Transition",system+"/"+name, ...
    "Position",position,"OutPortSampleTime",outSampleTime);
end

function wire(system,source,destination,name)
line=add_line(system,source,destination,"autorouting","on");
if strlength(name)>0; set_param(line,"Name",name); end
end

function ensureHarnessModels(root)
required=[ ...
    "ScenarioLibrary/Roadsense_ScenarioLibrary.slx", ...
    "ScenarioSensorSource/Roadsense_ScenarioSensorSource.slx", ...
    "ScenarioAdapters/Roadsense_ScenarioAdapters.slx"];
generators=["createRoadsenseScenarioLibraryModel", ...
    "createRoadsenseScenarioSensorSourceModel", ...
    "createRoadsenseScenarioAdaptersModel"];
for index=1:numel(required)
    if ~isfile(fullfile(root,"Models",required(index))); feval(generators(index)); end
end
integrationPath=fullfile(root,"Models","ClosedLoopIntegration", ...
    "Roadsense_ClosedLoopIntegration.slx");
regenerate=~isfile(integrationPath);
if ~regenerate
    load_system(integrationPath);
    regenerate=numel(find_system("Roadsense_ClosedLoopIntegration", ...
        "SearchDepth",1,"BlockType","Outport"))~=11;
    close_system("Roadsense_ClosedLoopIntegration",0);
end
if regenerate; createRoadsenseClosedLoopIntegrationModel(); end
end

function closeIfLoaded(modelName)
if bdIsLoaded(modelName); close_system(modelName,0); end
end
