function data=createSyntheticRoadsenseScenarioAdapterInputs()
%CREATESYNTHETICROADSENSESCENARIOADAPTERINPUTS Deterministic adapter inputs.
data=struct; data.CurrentTime=1.0;
[columns,rows]=meshgrid(uint16(0:639),uint16(0:479));
data.CameraImage=cat(3,uint8(mod(columns,256)),uint8(mod(rows,256)), ...
    uint8(80*ones(480,640))); data.CameraValid=true;
data.LidarPoints=zeros(120000,3,"single"); data.LidarIntensity=zeros(120000,1,"single");
data.LidarCount=uint32(8); data.LidarOverflow=false; data.LidarValid=true;
data.LidarPoints(1:8,:)=single([5 -1 0;5 0 0;5 1 0;10 -1 0; ...
    10 0 -0.1;10 1 0;15 -1 0;15 1 0]);
data.LidarIntensity(1:8)=single(linspace(0.2,0.9,8));
data.RadarPositions=zeros(256,3,"single"); data.RadarVelocities=zeros(256,3,"single");
data.RadarPositionCovariances=zeros(3,3,256,"single");
data.RadarVelocityCovariances=zeros(3,3,256,"single");
data.RadarScores=zeros(256,1,"single"); data.RadarCount=uint16(2);
data.RadarOverflow=false; data.RadarValid=true;
data.RadarPositions(1:2,:)=single([18 -1 0.5;30 2 0.5]);
data.RadarVelocities(1:2,:)=single([-2 0 0;1 0 0]);
data.RadarPositionCovariances(:,:,1)=single(diag([0.5 0.7 1.2].^2));
data.RadarPositionCovariances(:,:,2)=single(diag([0.8 0.8 1.5].^2));
data.RadarVelocityCovariances(:,:,1)=single(diag([1 1 1.5].^2));
data.RadarVelocityCovariances(:,:,2)=single(diag([1.5 1.5 2].^2));
data.RadarScores(1:2)=single([0.9;0.75]);

routeX=(0:2:100).'; routeY=2*sin(routeX/18); count=numel(routeX);
world=zeros(256,3); world(1:count,:)=[routeX routeY zeros(count,1)];
speeds=zeros(256,1,"single"); speeds(1:count)=single(8-2*(routeX/100));
mask=false(256,1); mask(1:count)=true;
data.ScenarioDefinition=struct("Timestamp",0,"ScenarioID",uint16(1), ...
    "Count",uint16(count),"WorldPositions",world, ...
    "RecommendedSpeeds",speeds,"ValidMask",mask, ...
    "DesiredSpeed",single(8),"SpeedLimit",single(10),"GoalRadius",single(1.5), ...
    "AllowObstacleAvoidance",true,"UncontrolledIntersection",false, ...
    "OccludedArea",false,"MergeRequired",false, ...
    "InitialPosition",[0;0;0],"InitialYaw",atan2(routeY(2)-routeY(1),2), ...
    "InitialSpeed",single(0),"FrictionCoefficient",single(0.8), ...
    "Grade",single(0),"Bank",single(0),"RollingResistance",single(0.015), ...
    "Valid",true);
data.EgoState=struct("Timestamp",data.CurrentTime,"Position",[0;0;0], ...
    "Velocity",[0;0;0],"Acceleration",[0;0;0], ...
    "Yaw",data.ScenarioDefinition.InitialYaw,"Pitch",0,"Roll",0, ...
    "YawRate",0,"SteeringAngle",0,"Valid",true);
data.ResetRequest=false;
end
