function contract = defineRoadsenseContract()
%DEFINEROADSENSECONTRACT Construct shared Roadsense buses and parameters.
%   CONTRACT = DEFINEROADSENSECONTRACT returns two structures, Buses and
%   Parameters. The function has no base-workspace side effects and is the
%   single source of truth used to populate Roadsense_Data.sldd.

arguments (Output)
    contract struct
end

limits = struct( ...
    "MaxDetections",256, ...
    "MaxTracks",128, ...
    "MaxPredictionModes",4, ...
    "PredictionSteps",16, ...
    "MaxPlanPoints",61, ...
    "CameraImageHeight",480, ...
    "CameraImageWidth",640, ...
    "SemanticOutputHeight",120, ...
    "SemanticOutputWidth",160, ...
    "MaxLidarPoints",120000, ...
    "GridResolution",0.25, ...
    "GridXLimits",[-20 60], ...
    "GridYLimits",[-25 25]);

limits.MaxReferencePoints = 256;
limits.MaxScenarioActors = 64;

limits.GridRows = round(diff(limits.GridYLimits)/limits.GridResolution);
limits.GridCols = round(diff(limits.GridXLimits)/limits.GridResolution);

buses = struct;

buses.RsCameraFrameBus = makeBus([ ...
    elem("Timestamp",1,"double","s","Camera exposure time."), ...
    elem("FrameID",1,"uint32","","Monotonically increasing camera frame identifier."), ...
    elem("Image",[limits.CameraImageHeight limits.CameraImageWidth 3],"uint8","","RGB image in row-column-channel order."), ...
    elem("Valid",1,"boolean","","True when the image and metadata are usable.")], ...
    "Fixed-size RGB camera frame and acquisition metadata.");

buses.RsImageSemanticBus = makeBus([ ...
    elem("Timestamp",1,"double","s","Source camera exposure time."), ...
    elem("FrameID",1,"uint32","","Source camera frame identifier."), ...
    elem("SemanticLabel",[limits.SemanticOutputHeight limits.SemanticOutputWidth],"uint8","","Numeric RoadsenseTypes.SemanticClass code."), ...
    elem("Confidence",[limits.SemanticOutputHeight limits.SemanticOutputWidth],"single","","Winning-class probability in [0,1].",0,1), ...
    elem("DrivableProbability",[limits.SemanticOutputHeight limits.SemanticOutputWidth],"single","","Road/drivable confidence in [0,1].",0,1), ...
    elem("InferenceTime",1,"single","s","Measured wall-clock semantic inference time."), ...
    elem("NetworkReady",1,"boolean","","True when a trained network was loaded."), ...
    elem("Valid",1,"boolean","","True when this output came from a valid image and successful inference.")], ...
    "Image-plane semantic evidence produced by camera AI.");

buses.RsCameraObjectListBus = makeBus([ ...
    elem("Timestamp",1,"double","s","Source camera exposure time."), ...
    elem("FrameID",1,"uint32","","Source camera frame identifier."), ...
    elem("Count",1,"uint16","","Number of valid leading object entries."), ...
    elem("BoundingBoxes",[limits.MaxDetections 4],"single","","Image boxes [x y width height] in pixels."), ...
    elem("ClassIDs",[limits.MaxDetections 1],"uint8","","Numeric RoadsenseTypes.ObjectClass code."), ...
    elem("Scores",[limits.MaxDetections 1],"single","","Detection confidence in [0,1].",0,1), ...
    elem("Positions",[limits.MaxDetections 3],"single","m","Approximate ego-frame [x y z] ground positions."), ...
    elem("PositionCovariances",[3 3 limits.MaxDetections],"single","m^2","Ground-position covariance per object."), ...
    elem("ValidMask",[limits.MaxDetections 1],"boolean","","True for each populated object slot."), ...
    elem("InputImageSize",[2 1],"uint16","","Input [height;width] in pixels."), ...
    elem("InferenceTime",1,"single","s","Shared semantic inference and postprocessing time."), ...
    elem("NetworkReady",1,"boolean","","True when a trained network was loaded."), ...
    elem("Overflow",1,"boolean","","True when object regions exceeded capacity."), ...
    elem("Valid",1,"boolean","","True when this output came from successful inference.")], ...
    "Camera object regions derived from semantic AI or a future dedicated detector.");

buses.RsLidarFrameBus = makeBus([ ...
    elem("Timestamp",1,"double","s","LiDAR acquisition time."), ...
    elem("FrameID",1,"uint32","","Monotonically increasing LiDAR frame identifier."), ...
    elem("Count",1,"uint32","","Number of valid leading point entries."), ...
    elem("Points",[limits.MaxLidarPoints 3],"single","m","Ego-frame [forward left up] points."), ...
    elem("Intensity",[limits.MaxLidarPoints 1],"single","","Normalized return intensity in [0,1].",0,1), ...
    elem("Overflow",1,"boolean","","True when the source scan exceeded fixed capacity."), ...
    elem("Valid",1,"boolean","","True when metadata and point data are usable.")], ...
    "Normalized, fixed-capacity LiDAR point cloud.");

buses.RsLidarGridEvidenceBus = makeBus([ ...
    elem("Timestamp",1,"double","s","Source LiDAR acquisition time."), ...
    elem("FrameID",1,"uint32","","Source LiDAR frame identifier."), ...
    elem("Resolution",1,"single","m","Metres per grid cell."), ...
    elem("XLimits",[2 1],"single","m","Longitudinal ego-frame bounds [min;max]."), ...
    elem("YLimits",[2 1],"single","m","Lateral ego-frame bounds [min;max]."), ...
    elem("Occupancy",[limits.GridRows limits.GridCols],"single","","Non-ground occupancy confidence in [0,1].",0,1), ...
    elem("GroundHeight",[limits.GridRows limits.GridCols],"single","m","Observed ground height relative to ego origin."), ...
    elem("Roughness",[limits.GridRows limits.GridCols],"single","m","Ground-height standard deviation."), ...
    elem("PotholeProbability",[limits.GridRows limits.GridCols],"single","","Depressed-surface probability in [0,1].",0,1), ...
    elem("SurfaceCost",[limits.GridRows limits.GridCols],"single","","Combined roughness/depression cost in [0,1].",0,1), ...
    elem("ObservedMask",[limits.GridRows limits.GridCols],"boolean","","Cells containing at least one LiDAR return."), ...
    elem("ProcessingTime",1,"single","s","Measured wall-clock processing time."), ...
    elem("Valid",1,"boolean","","True when grid evidence was produced successfully.")], ...
    "LiDAR-derived occupancy and road-surface evidence in the ego grid.");

buses.RsLidarObjectListBus = makeBus([ ...
    elem("Timestamp",1,"double","s","Source LiDAR acquisition time."), ...
    elem("FrameID",1,"uint32","","Source LiDAR frame identifier."), ...
    elem("Count",1,"uint16","","Number of valid leading object entries."), ...
    elem("Positions",[limits.MaxDetections 3],"single","m","Ego-frame cluster centroids."), ...
    elem("Dimensions",[limits.MaxDetections 3],"single","m","Oriented [length width height] estimates."), ...
    elem("Yaws",[limits.MaxDetections 1],"single","rad","Principal-axis cluster headings."), ...
    elem("ClassIDs",[limits.MaxDetections 1],"uint8","","Numeric RoadsenseTypes.ObjectClass; unknown until classified."), ...
    elem("Scores",[limits.MaxDetections 1],"single","","Geometric detection confidence in [0,1].",0,1), ...
    elem("PositionCovariances",[3 3 limits.MaxDetections],"single","m^2","Centroid covariance per cluster."), ...
    elem("PointCounts",[limits.MaxDetections 1],"uint32","","Number of LiDAR returns in each cluster."), ...
    elem("ValidMask",[limits.MaxDetections 1],"boolean","","True for each populated cluster slot."), ...
    elem("ProcessingTime",1,"single","s","Shared segmentation and clustering time."), ...
    elem("Overflow",1,"boolean","","True when clusters exceeded capacity."), ...
    elem("Valid",1,"boolean","","True when this output came from a valid scan.")], ...
    "Geometric object clusters produced by LiDAR perception.");

buses.RsRadarObjectListBus = makeBus([ ...
    elem("Timestamp",1,"double","s","Radar measurement time."), ...
    elem("FrameID",1,"uint32","","Monotonically increasing radar frame identifier."), ...
    elem("Count",1,"uint16","","Number of valid leading object entries."), ...
    elem("Positions",[limits.MaxDetections 3],"single","m","Ego-frame radar positions [forward left up]."), ...
    elem("Velocities",[limits.MaxDetections 3],"single","m/s","Ego-frame Cartesian velocity measurements."), ...
    elem("PositionCovariances",[3 3 limits.MaxDetections],"single","m^2","Position covariance per radar detection."), ...
    elem("VelocityCovariances",[3 3 limits.MaxDetections],"single","(m/s)^2","Velocity covariance per radar detection."), ...
    elem("Scores",[limits.MaxDetections 1],"single","","Radar detection confidence in [0,1].",0,1), ...
    elem("ValidMask",[limits.MaxDetections 1],"boolean","","True for each populated radar slot."), ...
    elem("Overflow",1,"boolean","","True when radar detections exceeded capacity."), ...
    elem("Valid",1,"boolean","","True when radar data and metadata are usable.")], ...
    "Fixed-capacity Cartesian radar detections for multi-sensor fusion.");

buses.RsEgoStateBus = makeBus([ ...
    elem("Timestamp",1,"double","s","Scenario time."), ...
    elem("Position",[3 1],"double","m","Ego position [x;y;z] in the local world frame."), ...
    elem("Velocity",[3 1],"double","m/s","Ego velocity [vx;vy;vz] in the local world frame."), ...
    elem("Acceleration",[3 1],"double","m/s^2","Ego acceleration [ax;ay;az] in the local world frame."), ...
    elem("Yaw",1,"double","rad","Counter-clockwise heading from +x."), ...
    elem("Pitch",1,"double","rad","Ego pitch."), ...
    elem("Roll",1,"double","rad","Ego roll."), ...
    elem("YawRate",1,"double","rad/s","Ego yaw rate."), ...
    elem("SteeringAngle",1,"double","rad","Road-wheel steering angle."), ...
    elem("Valid",1,"boolean","","True when this sample is usable.")], ...
    "Time-stamped ego motion state.");

buses.RsRouteContextBus = makeBus([ ...
    elem("Timestamp",1,"double","s","High-level route-context time."), ...
    elem("DesiredSpeed",1,"single","m/s","Requested free-flow route speed."), ...
    elem("SpeedLimit",1,"single","m/s","Current legal or scenario speed limit."), ...
    elem("DistanceToGoal",1,"single","m","Remaining route distance."), ...
    elem("GoalReached",1,"boolean","","True when the final stopping region is reached."), ...
    elem("AllowObstacleAvoidance",1,"boolean","","True when lateral obstacle avoidance is route-permitted."), ...
    elem("UncontrolledIntersection",1,"boolean","","True inside an unsignalized or informally controlled junction."), ...
    elem("OccludedArea",1,"boolean","","True when visibility is insufficient for normal-speed entry."), ...
    elem("MergeRequired",1,"boolean","","True while performing an informal or highway merge."), ...
    elem("Valid",1,"boolean","","True when route context is current and usable.")], ...
    "Map-independent high-level route and scenario context.");

buses.RsReferencePathBus = makeBus([ ...
    elem("Timestamp",1,"double","s","Reference-path generation time."), ...
    elem("Count",1,"uint16","","Number of valid leading path samples."), ...
    elem("Positions",[limits.MaxReferencePoints 2],"single","m","Current-ego-frame route guidance positions [x y]."), ...
    elem("Yaws",[limits.MaxReferencePoints 1],"single","rad","Route headings relative to current ego heading."), ...
    elem("RecommendedSpeeds",[limits.MaxReferencePoints 1],"single","m/s","Optional route speed profile."), ...
    elem("ValidMask",[limits.MaxReferencePoints 1],"boolean","","True for each populated reference sample."), ...
    elem("Valid",1,"boolean","","True when the reference polyline is usable.")], ...
    "Lane-independent local route polyline expressed in the current ego frame.");

buses.RsSensorDetectionBus = makeBus([ ...
    elem("Timestamp",1,"double","s","Measurement time."), ...
    elem("DetectionID",1,"uint32","","Detection identifier local to its source."), ...
    elem("SensorID",1,"uint16","","Unique sensor identifier."), ...
    elem("SensorType",1,"Enum: RoadsenseTypes.SensorType","","Measurement source."), ...
    elem("ClassID",1,"Enum: RoadsenseTypes.ObjectClass","","Most probable semantic class."), ...
    elem("ClassConfidence",1,"single","","Class probability in [0,1].",0,1), ...
    elem("Position",[3 1],"single","m","Measured [x;y;z] in ego coordinates."), ...
    elem("Velocity",[3 1],"single","m/s","Measured velocity in ego coordinates."), ...
    elem("Dimensions",[3 1],"single","m","Object [length;width;height]."), ...
    elem("Yaw",1,"single","rad","Object heading relative to ego +x."), ...
    elem("PositionCovariance",[3 3],"single","m^2","Position measurement covariance."), ...
    elem("VelocityCovariance",[3 3],"single","(m/s)^2","Velocity measurement covariance."), ...
    elem("HasVelocity",1,"boolean","","True when velocity is measured."), ...
    elem("Valid",1,"boolean","","True when this array slot contains a detection.")], ...
    "Normalized detection emitted by camera, lidar, radar, or reference sensing.");

buses.RsSensorDetectionArrayBus = makeBus([ ...
    elem("Timestamp",1,"double","s","Array assembly time."), ...
    elem("Count",1,"uint16","","Number of valid leading entries."), ...
    elem("Detections",[limits.MaxDetections 1],"Bus: RsSensorDetectionBus","","Fixed-capacity detection array."), ...
    elem("Overflow",1,"boolean","","True when detections exceeded capacity.")], ...
    "Fixed-capacity collection of normalized sensor detections.");

buses.RsTrackedObjectBus = makeBus([ ...
    elem("Timestamp",1,"double","s","Most recent filter time."), ...
    elem("TrackID",1,"uint32","","Persistent tracker identifier."), ...
    elem("ClassID",1,"Enum: RoadsenseTypes.ObjectClass","","Fused semantic class."), ...
    elem("ClassConfidence",1,"single","","Fused class probability in [0,1].",0,1), ...
    elem("ExistenceProbability",1,"single","","Track existence probability in [0,1].",0,1), ...
    elem("Position",[3 1],"single","m","Estimated [x;y;z] in ego coordinates."), ...
    elem("Velocity",[3 1],"single","m/s","Estimated velocity in ego coordinates."), ...
    elem("Acceleration",[3 1],"single","m/s^2","Estimated acceleration in ego coordinates."), ...
    elem("Yaw",1,"single","rad","Estimated object heading relative to ego +x."), ...
    elem("YawRate",1,"single","rad/s","Estimated object yaw rate."), ...
    elem("Dimensions",[3 1],"single","m","Estimated [length;width;height]."), ...
    elem("StateCovariance",[6 6],"single","","Covariance of [x;y;z;vx;vy;vz]."), ...
    elem("Age",1,"uint16","","Number of tracker update cycles."), ...
    elem("SensorMask",1,"uint8","","Bit mask: camera=1, lidar=2, radar=4."), ...
    elem("IsConfirmed",1,"boolean","","Tracker confirmation state."), ...
    elem("Valid",1,"boolean","","True when this array slot contains a track.")], ...
    "Fused, time-stamped dynamic or static object track.");

buses.RsTrackedObjectArrayBus = makeBus([ ...
    elem("Timestamp",1,"double","s","Tracker output time."), ...
    elem("Count",1,"uint16","","Number of valid leading entries."), ...
    elem("Objects",[limits.MaxTracks 1],"Bus: RsTrackedObjectBus","","Fixed-capacity track array."), ...
    elem("Overflow",1,"boolean","","True when tracks exceeded capacity.")], ...
    "Fixed-capacity collection of fused object tracks.");

buses.RsFusedTrackListBus = makeBus([ ...
    elem("Timestamp",1,"double","s","Fusion update time."), ...
    elem("Count",1,"uint16","","Number of valid leading track entries."), ...
    elem("TrackIDs",[limits.MaxTracks 1],"uint32","","Persistent JPDA track identifiers."), ...
    elem("ClassIDs",[limits.MaxTracks 1],"uint8","","Numeric RoadsenseTypes.ObjectClass codes."), ...
    elem("ClassConfidences",[limits.MaxTracks 1],"single","","Maximum fused class probability in [0,1].",0,1), ...
    elem("ExistenceProbabilities",[limits.MaxTracks 1],"single","","JIPDA existence probability in [0,1].",0,1), ...
    elem("Positions",[limits.MaxTracks 3],"single","m","Estimated ego-frame [x y z] positions."), ...
    elem("Velocities",[limits.MaxTracks 3],"single","m/s","Estimated ego-frame Cartesian velocities."), ...
    elem("Accelerations",[limits.MaxTracks 3],"single","m/s^2","Estimated acceleration; zero until an acceleration model is enabled."), ...
    elem("Yaws",[limits.MaxTracks 1],"single","rad","Velocity-derived object headings."), ...
    elem("YawRates",[limits.MaxTracks 1],"single","rad/s","Estimated yaw rates; zero for the present Cartesian IMM."), ...
    elem("Dimensions",[limits.MaxTracks 3],"single","m","Persisted [length width height] estimates."), ...
    elem("StateCovariances",[6 6 limits.MaxTracks],"single","","Covariance ordered [x y z vx vy vz]."), ...
    elem("Ages",[limits.MaxTracks 1],"uint16","","Number of tracker update cycles."), ...
    elem("SensorMasks",[limits.MaxTracks 1],"uint8","","Current supporting sensors: camera=1, lidar=2, radar=4."), ...
    elem("IsConfirmed",[limits.MaxTracks 1],"boolean","","True after the probabilistic confirmation threshold is met."), ...
    elem("ValidMask",[limits.MaxTracks 1],"boolean","","True for each populated output track."), ...
    elem("ProcessingTime",1,"single","s","Measured wall-clock association and tracking time."), ...
    elem("SourceOverflow",1,"boolean","","True when any upstream object list overflowed."), ...
    elem("Overflow",1,"boolean","","True when output tracks exceeded fixed capacity."), ...
    elem("Valid",1,"boolean","","True when the fusion update executed with a valid timestamp.")], ...
    "Flat fixed-capacity fused-track interface used by prediction and planning.");

buses.RsPredictedTrajectoryBus = makeBus([ ...
    elem("Timestamp",1,"double","s","Prediction generation time."), ...
    elem("TrackID",1,"uint32","","Source track identifier."), ...
    elem("ClassID",1,"Enum: RoadsenseTypes.ObjectClass","","Source semantic class."), ...
    elem("NumModes",1,"uint8","","Number of valid leading motion modes."), ...
    elem("NumSteps",1,"uint8","","Number of valid leading time steps."), ...
    elem("TimeOffsets",[limits.PredictionSteps 1],"single","s","Future time relative to Timestamp."), ...
    elem("ModeProbabilities",[limits.MaxPredictionModes 1],"single","","Mode probabilities; valid values sum to one."), ...
    elem("Positions",[2 limits.PredictionSteps limits.MaxPredictionModes],"single","m","Predicted ego-frame [x;y] by step and mode."), ...
    elem("Yaws",[limits.PredictionSteps limits.MaxPredictionModes],"single","rad","Predicted headings by step and mode."), ...
    elem("PositionCovariances",[2 2 limits.PredictionSteps limits.MaxPredictionModes],"single","m^2","Predicted 2-D covariance by step and mode."), ...
    elem("Valid",1,"boolean","","True when this array slot contains a prediction.")], ...
    "Fixed-horizon multimodal prediction for one tracked object.");

buses.RsPredictionArrayBus = makeBus([ ...
    elem("Timestamp",1,"double","s","Prediction output time."), ...
    elem("Count",1,"uint16","","Number of valid leading entries."), ...
    elem("Predictions",[limits.MaxTracks 1],"Bus: RsPredictedTrajectoryBus","","One prediction slot per possible track."), ...
    elem("Overflow",1,"boolean","","True when predictions exceeded capacity.")], ...
    "Fixed-capacity collection of object predictions.");

buses.RsMotionPredictionListBus = makeBus([ ...
    elem("Timestamp",1,"double","s","Prediction generation time."), ...
    elem("Count",1,"uint16","","Number of valid leading predicted objects."), ...
    elem("TrackIDs",[limits.MaxTracks 1],"uint32","","Source fused-track identifiers."), ...
    elem("ClassIDs",[limits.MaxTracks 1],"uint8","","Numeric RoadsenseTypes.ObjectClass codes."), ...
    elem("NumModes",[limits.MaxTracks 1],"uint8","","Number of valid modes for each object."), ...
    elem("NumSteps",1,"uint8","","Number of valid common prediction samples."), ...
    elem("TimeOffsets",[limits.PredictionSteps 1],"single","s","Future times relative to Timestamp."), ...
    elem("ModeProbabilities",[limits.MaxTracks limits.MaxPredictionModes],"single","","Per-object mode probabilities; valid rows sum to one.",0,1), ...
    elem("Positions",[limits.MaxTracks limits.PredictionSteps limits.MaxPredictionModes 2],"single","m","Predicted current-ego-frame [x y] positions."), ...
    elem("Yaws",[limits.MaxTracks limits.PredictionSteps limits.MaxPredictionModes],"single","rad","Predicted headings by object, step, and mode."), ...
    elem("PositionCovariances",[2 2 limits.PredictionSteps limits.MaxPredictionModes limits.MaxTracks],"single","m^2","Per-mode 2-D position covariance."), ...
    elem("ValidMask",[limits.MaxTracks 1],"boolean","","True for each populated prediction slot."), ...
    elem("ProcessingTime",1,"single","s","Measured wall-clock prediction time."), ...
    elem("Overflow",1,"boolean","","True when input tracks exceeded prediction capacity."), ...
    elem("Valid",1,"boolean","","True when prediction completed for a valid track list.")], ...
    "Flat fixed-capacity multimodal motion predictions for map and planner use.");

buses.RsSemanticGridBus = makeBus([ ...
    elem("Timestamp",1,"double","s","Grid fusion time."), ...
    elem("Resolution",1,"single","m","Metres per grid cell."), ...
    elem("XLimits",[2 1],"single","m","Longitudinal ego-frame bounds [min;max]."), ...
    elem("YLimits",[2 1],"single","m","Lateral ego-frame bounds [min;max]."), ...
    elem("StaticOccupancy",[limits.GridRows limits.GridCols],"single","","LiDAR/static occupancy probability in [0,1].",0,1), ...
    elem("DynamicOccupancy",[limits.GridRows limits.GridCols],"single","","Current tracked-object footprint occupancy in [0,1].",0,1), ...
    elem("PredictedRisk",[limits.GridRows limits.GridCols],"single","","Time-decayed multimodal future occupancy risk in [0,1].",0,1), ...
    elem("Occupancy",[limits.GridRows limits.GridCols],"single","","Combined current static and dynamic occupancy in [0,1].",0,1), ...
    elem("Drivability",[limits.GridRows limits.GridCols],"single","","Drivable probability in [0,1].",0,1), ...
    elem("SurfaceCost",[limits.GridRows limits.GridCols],"single","","Normalized surface penalty in [0,1].",0,1), ...
    elem("CombinedCost",[limits.GridRows limits.GridCols],"single","","Combined occupancy, future-risk, surface, and non-drivability cost.",0,1), ...
    elem("SemanticLabel",[limits.GridRows limits.GridCols],"uint8","","Numeric RoadsenseTypes.SemanticClass code."), ...
    elem("ObservedMask",[limits.GridRows limits.GridCols],"boolean","","True for cells observed by at least one sensor."), ...
    elem("ProcessingTime",1,"single","s","Measured wall-clock map-fusion time."), ...
    elem("SourceOverflow",1,"boolean","","True when any bounded upstream list overflowed."), ...
    elem("Valid",1,"boolean","","True when geometry and grid channels are consistent.")], ...
    "Ego-fixed semantic traversability grid. Rows increase with +y; columns with +x.");

buses.RsTrajectoryPointBus = makeBus([ ...
    elem("TimeFromStart",1,"single","s","Time relative to plan Timestamp."), ...
    elem("Position",[2 1],"single","m","Planned local-world [x;y]."), ...
    elem("Yaw",1,"single","rad","Planned heading."), ...
    elem("Speed",1,"single","m/s","Planned signed speed."), ...
    elem("Acceleration",1,"single","m/s^2","Planned longitudinal acceleration."), ...
    elem("Curvature",1,"single","1/m","Planned path curvature."), ...
    elem("SteeringAngle",1,"single","rad","Feed-forward road-wheel angle.")], ...
    "One time-parameterized ego trajectory sample.");

buses.RsPlannedTrajectoryBus = makeBus([ ...
    elem("Timestamp",1,"double","s","Plan generation time."), ...
    elem("PlanID",1,"uint32","","Monotonically increasing plan identifier."), ...
    elem("Count",1,"uint16","","Number of valid leading points."), ...
    elem("Points",[limits.MaxPlanPoints 1],"Bus: RsTrajectoryPointBus","","Fixed-capacity trajectory points."), ...
    elem("TotalCost",1,"single","","Winning candidate cost."), ...
    elem("MinimumClearance",1,"single","m","Predicted minimum footprint clearance."), ...
    elem("Valid",1,"boolean","","True when the trajectory is safe and feasible.")], ...
    "Selected, time-parameterized ego trajectory.");

buses.RsLocalPlanBus = makeBus([ ...
    elem("Timestamp",1,"double","s","Plan generation time."), ...
    elem("PlanID",1,"uint32","","Monotonically increasing local-plan identifier."), ...
    elem("Count",1,"uint16","","Number of valid leading trajectory samples."), ...
    elem("TimeFromStart",[limits.MaxPlanPoints 1],"single","s","Trajectory time relative to Timestamp."), ...
    elem("Positions",[limits.MaxPlanPoints 2],"single","m","Selected local-world positions [x y]."), ...
    elem("Yaws",[limits.MaxPlanPoints 1],"single","rad","Selected local-world headings."), ...
    elem("Speeds",[limits.MaxPlanPoints 1],"single","m/s","Planned nonnegative longitudinal speed."), ...
    elem("Accelerations",[limits.MaxPlanPoints 1],"single","m/s^2","Planned longitudinal acceleration."), ...
    elem("Curvatures",[limits.MaxPlanPoints 1],"single","1/m","Signed path curvature."), ...
    elem("SteeringAngles",[limits.MaxPlanPoints 1],"single","rad","Bicycle-model feed-forward road-wheel angle."), ...
    elem("TotalCost",1,"single","","Winning candidate objective value."), ...
    elem("MinimumClearance",1,"single","m","Minimum predicted footprint clearance."), ...
    elem("CandidateCount",1,"uint16","","Number of sampled candidate trajectories."), ...
    elem("FeasibleCount",1,"uint16","","Candidates passing all hard constraints."), ...
    elem("EmergencyFallback",1,"boolean","","True when the minimum-risk braking fallback was used."), ...
    elem("Valid",1,"boolean","","True when a bounded trajectory was produced.")], ...
    "Flat selected local trajectory and planner diagnostics.");

buses.RsPlannerStatusBus = makeBus([ ...
    elem("Timestamp",1,"double","s","Status generation time."), ...
    elem("PlanID",1,"uint32","","Associated plan identifier."), ...
    elem("Code",1,"Enum: RoadsenseTypes.PlannerCode","","Planner outcome."), ...
    elem("Behaviour",1,"Enum: RoadsenseTypes.BehaviourMode","","Active supervisory state."), ...
    elem("CandidateCount",1,"uint16","","Candidates evaluated."), ...
    elem("FeasibleCount",1,"uint16","","Candidates passing all hard constraints."), ...
    elem("ExecutionTime",1,"single","s","Measured wall-clock planning latency."), ...
    elem("Deadline",1,"single","s","Allowed planning latency."), ...
    elem("ReplanRequested",1,"boolean","","True when another plan is required."), ...
    elem("EmergencyRequested",1,"boolean","","True when safety fallback is required.")], ...
    "Planner health, timing, and decision status.");

buses.RsBehaviourCommandBus = makeBus([ ...
    elem("Timestamp",1,"double","s","Behaviour decision time."), ...
    elem("SequenceID",1,"uint32","","Incremented whenever the supervisory mode changes."), ...
    elem("Mode",1,"Enum: RoadsenseTypes.BehaviourMode","","Selected supervisory driving mode."), ...
    elem("TargetSpeed",1,"single","m/s","Speed objective supplied to trajectory generation."), ...
    elem("MaximumAcceleration",1,"single","m/s^2","Upper longitudinal acceleration bound."), ...
    elem("MinimumAcceleration",1,"single","m/s^2","Lower longitudinal acceleration bound."), ...
    elem("DesiredClearance",1,"single","m","Minimum preferred obstacle clearance."), ...
    elem("StopDistance",1,"single","m","Current conservative stopping-distance estimate."), ...
    elem("LeadTrackID",1,"uint32","","Selected lead object; zero when none."), ...
    elem("MinimumTTC",1,"single","s","Minimum estimated time to collision; Inf when none."), ...
    elem("ForwardRisk",1,"single","","Maximum relevant forward map risk in [0,1].",0,1), ...
    elem("UnknownFraction",1,"single","","Fraction of the forward corridor not directly observed.",0,1), ...
    elem("ReasonMask",1,"uint16","","Decision causes: invalid=1, collision=2, goal=4, vulnerable=8, lead=16, blocked=32, unknown=64, surface=128, junction=256."), ...
    elem("ReplanRequested",1,"boolean","","True on a supervisory mode transition."), ...
    elem("EmergencyRequested",1,"boolean","","True while emergency braking is commanded."), ...
    elem("Valid",1,"boolean","","True when the command is safe to consume.")], ...
    "Stateful supervisory command consumed by local trajectory planning.");

buses.RsVehicleControlBus = makeBus([ ...
    elem("Timestamp",1,"double","s","Control-command generation time."), ...
    elem("PlanID",1,"uint32","","Plan being tracked."), ...
    elem("SteeringAngle",1,"single","rad","Requested road-wheel steering angle."), ...
    elem("SteeringRate",1,"single","rad/s","Applied steering-angle rate."), ...
    elem("AccelerationCommand",1,"single","m/s^2","Requested signed longitudinal acceleration."), ...
    elem("Throttle",1,"single","","Normalized propulsion command in [0,1].",0,1), ...
    elem("Brake",1,"single","","Normalized service-brake command in [0,1].",0,1), ...
    elem("TargetSpeed",1,"single","m/s","Active trajectory speed target."), ...
    elem("EmergencyStop",1,"boolean","","True when the fail-safe braking command is active."), ...
    elem("Valid",1,"boolean","","True when the command was generated from valid current state and plan data.")], ...
    "Actuator-neutral steering and longitudinal request from trajectory control.");

buses.RsTrackingStatusBus = makeBus([ ...
    elem("Timestamp",1,"double","s","Tracking-status generation time."), ...
    elem("PlanID",1,"uint32","","Plan being tracked."), ...
    elem("ReferenceIndex",1,"uint16","","Selected trajectory reference sample."), ...
    elem("CrossTrackError",1,"single","m","Signed path-normal ego displacement."), ...
    elem("HeadingError",1,"single","rad","Wrapped reference-minus-ego heading error."), ...
    elem("SpeedError",1,"single","m/s","Reference-minus-ego longitudinal speed."), ...
    elem("ReferenceCurvature",1,"single","1/m","Selected trajectory curvature."), ...
    elem("ReferenceAge",1,"single","s","Elapsed time since plan generation."), ...
    elem("SteeringSaturated",1,"boolean","","True when angle or rate limiting changed steering."), ...
    elem("AccelerationSaturated",1,"boolean","","True when acceleration or slew limiting changed the command."), ...
    elem("PlanExpired",1,"boolean","","True when the trajectory horizon plus grace time elapsed."), ...
    elem("Valid",1,"boolean","","True when errors were computed from usable state and plan inputs.")], ...
    "Closed-loop trajectory tracking errors, reference selection, and limiter state.");

buses.RsRoadConditionBus = makeBus([ ...
    elem("Timestamp",1,"double","s","Road-condition sample time."), ...
    elem("FrictionCoefficient",1,"single","","Tyre-road friction coefficient."), ...
    elem("Grade",1,"single","rad","Positive uphill longitudinal grade angle."), ...
    elem("Bank",1,"single","rad","Positive left-up road bank angle."), ...
    elem("RollingResistance",1,"single","","Rolling-resistance coefficient."), ...
    elem("Valid",1,"boolean","","True when the road-condition sample is usable.")], ...
    "Local friction, grade, bank, and rolling resistance for vehicle simulation.");

buses.RsVehicleDynamicsStatusBus = makeBus([ ...
    elem("Timestamp",1,"double","s","Vehicle-dynamics state time."), ...
    elem("LongitudinalSpeed",1,"single","m/s","Body-frame forward speed."), ...
    elem("LateralSpeed",1,"single","m/s","Body-frame leftward speed."), ...
    elem("SideslipAngle",1,"single","rad","Vehicle centre-of-mass sideslip angle."), ...
    elem("FrontSlipAngle",1,"single","rad","Front-tyre slip angle."), ...
    elem("RearSlipAngle",1,"single","rad","Rear-tyre slip angle."), ...
    elem("YawAcceleration",1,"single","rad/s^2","Yaw angular acceleration."), ...
    elem("LongitudinalAcceleration",1,"single","m/s^2","Body-frame inertial longitudinal acceleration."), ...
    elem("LateralAcceleration",1,"single","m/s^2","Body-frame inertial lateral acceleration."), ...
    elem("FrictionUtilization",1,"single","","Combined force divided by friction capacity."), ...
    elem("SteeringState",1,"single","rad","Simulated road-wheel steering state."), ...
    elem("ResetApplied",1,"boolean","","True when initial state was loaded this sample."), ...
    elem("TireForceSaturated",1,"boolean","","True when a tyre or friction-circle force was limited."), ...
    elem("Valid",1,"boolean","","True when the simulated state is finite and usable.")], ...
    "Dynamic-bicycle internal state and physical-limit diagnostics.");

buses.RsSafetyStatusBus = makeBus([ ...
    elem("Timestamp",1,"double","s","Safety-supervisor decision time."), ...
    elem("SequenceID",1,"uint32","","Incremented whenever the safety state changes."), ...
    elem("State",1,"Enum: RoadsenseTypes.SafetyState","","Active independent safety state."), ...
    elem("ReasonMask",1,"uint16","","Safety causes: invalid=1, stale=2, collision=4, requested=8, tracking=16, instability=32, saturation=64, deadline=128, high-risk=256."), ...
    elem("MinimumTTC",1,"single","s","Independent minimum forward time to collision."), ...
    elem("NearestDistance",1,"single","m","Nearest relevant forward-object clearance."), ...
    elem("MaximumInputAge",1,"single","s","Largest nonnegative monitored signal age."), ...
    elem("CrossTrackError",1,"single","m","Controller-reported signed cross-track error."), ...
    elem("SideslipAngle",1,"single","rad","Vehicle-model centre-of-mass sideslip."), ...
    elem("FrictionUtilization",1,"single","","Vehicle combined-friction utilization."), ...
    elem("OverrideActive",1,"boolean","","True when nominal control was modified."), ...
    elem("EmergencyLatched",1,"boolean","","True while emergency braking is held after its trigger clears."), ...
    elem("SafeToDrive",1,"boolean","","True only in Normal or Degraded with valid monitored inputs."), ...
    elem("Valid",1,"boolean","","True when the supervisor emitted a deterministic decision.")], ...
    "Independent safety decision, trigger evidence, and override state.");

buses.RsIntegrationStatusBus = makeBus([ ...
    elem("Timestamp",1,"double","s","Current closed-loop vehicle time."), ...
    elem("CycleID",1,"uint32","","Monotonically increasing 50 Hz integration cycle identifier."), ...
    elem("PerceptionValid",1,"boolean","","True when camera and LiDAR perception outputs are usable."), ...
    elem("FusionValid",1,"boolean","","True when the fused-track list is usable."), ...
    elem("PredictionValid",1,"boolean","","True when the motion-prediction list is usable."), ...
    elem("MapValid",1,"boolean","","True when the semantic occupancy grid is usable."), ...
    elem("BehaviourValid",1,"boolean","","True when the behaviour command is usable."), ...
    elem("PlanValid",1,"boolean","","True when the local plan and planner status are usable."), ...
    elem("TrackingValid",1,"boolean","","True when nominal control and tracking status are usable."), ...
    elem("SafetyValid",1,"boolean","","True when safety status and the gated command are usable."), ...
    elem("VehicleValid",1,"boolean","","True when ego state and vehicle-dynamics status are usable."), ...
    elem("PipelineReady",1,"boolean","","True when every closed-loop component is currently usable."), ...
    elem("SafetyOverride",1,"boolean","","True when the safety supervisor is modifying nominal control."), ...
    elem("EmergencyStop",1,"boolean","","True when the final command requests fail-safe braking."), ...
    elem("GoalReached",1,"boolean","","True when valid route context reports completion."), ...
    elem("Valid",1,"boolean","","True when the integration monitor emitted a deterministic status.")], ...
    "End-to-end health, readiness, intervention, and completion summary.");

buses.RsScenarioDefinitionBus = makeBus([ ...
    elem("Timestamp",1,"double","s","Scenario-definition update time."), ...
    elem("ScenarioID",1,"uint16","","Identifier changed whenever a scenario is restarted or replaced."), ...
    elem("Count",1,"uint16","","Number of valid leading world-route points."), ...
    elem("WorldPositions",[limits.MaxReferencePoints 3],"double","m","World-frame route points [x y z]."), ...
    elem("RecommendedSpeeds",[limits.MaxReferencePoints 1],"single","m/s","Route speed recommendation at each point."), ...
    elem("ValidMask",[limits.MaxReferencePoints 1],"boolean","","True for each populated route-point slot."), ...
    elem("DesiredSpeed",1,"single","m/s","Scenario free-flow speed request."), ...
    elem("SpeedLimit",1,"single","m/s","Scenario speed limit."), ...
    elem("GoalRadius",1,"single","m","Distance from final point considered goal completion."), ...
    elem("AllowObstacleAvoidance",1,"boolean","","True when leaving the route centreline to avoid obstacles is permitted."), ...
    elem("UncontrolledIntersection",1,"boolean","","True in an unsignalized or informally controlled junction."), ...
    elem("OccludedArea",1,"boolean","","True when scenario visibility requires cautious entry."), ...
    elem("MergeRequired",1,"boolean","","True while the scenario requires an informal or highway merge."), ...
    elem("InitialPosition",[3 1],"double","m","Initial ego world position [x;y;z]."), ...
    elem("InitialYaw",1,"double","rad","Initial ego world heading."), ...
    elem("InitialSpeed",1,"single","m/s","Initial ego longitudinal speed."), ...
    elem("FrictionCoefficient",1,"single","","Tyre-road friction coefficient."), ...
    elem("Grade",1,"single","rad","Positive uphill road grade."), ...
    elem("Bank",1,"single","rad","Positive left-up road bank."), ...
    elem("RollingResistance",1,"single","","Road rolling-resistance coefficient."), ...
    elem("Valid",1,"boolean","","True when route, initialization, and road fields are usable.")], ...
    "Static or slowly varying scenario definition consumed by scenario adapters.");

buses.RsScenarioActorListBus = makeBus([ ...
    elem("Timestamp",1,"double","s","Scenario truth-sample time."), ...
    elem("Count",1,"uint16","","Number of valid leading actor entries."), ...
    elem("ActorIDs",[limits.MaxScenarioActors 1],"uint32","","Persistent scenario actor identifiers."), ...
    elem("ClassIDs",[limits.MaxScenarioActors 1],"uint8","","Numeric RoadsenseTypes.ObjectClass codes."), ...
    elem("Positions",[limits.MaxScenarioActors 3],"double","m","Actor world-frame positions [x y z]."), ...
    elem("Velocities",[limits.MaxScenarioActors 3],"single","m/s","Actor world-frame Cartesian velocities."), ...
    elem("Yaws",[limits.MaxScenarioActors 1],"single","rad","Actor world-frame headings."), ...
    elem("Dimensions",[limits.MaxScenarioActors 3],"single","m","Actor [length width height]."), ...
    elem("ValidMask",[limits.MaxScenarioActors 1],"boolean","","True for each active actor slot."), ...
    elem("Overflow",1,"boolean","","True when active actors exceeded fixed capacity."), ...
    elem("Valid",1,"boolean","","True when scenario truth is usable.")], ...
    "Fixed-capacity world-frame truth actors used by synthetic sensors and validation.");

buses.RsScenarioStatusBus = makeBus([ ...
    elem("Timestamp",1,"double","s","Scenario-library sample time."), ...
    elem("ScenarioID",1,"uint16","","Selected scenario identifier."), ...
    elem("ElapsedTime",1,"single","s","Time since scenario start."), ...
    elem("Duration",1,"single","s","Configured scenario duration."), ...
    elem("EventMask",1,"uint16","","Active events: running=1, unstructured=2, merge=4, pedestrian=8, animal=16, slow vehicle=32, surface hazard=64, complete=128."), ...
    elem("ActiveActorCount",1,"uint16","","Number of active truth actors."), ...
    elem("Valid",1,"boolean","","True when a supported scenario is selected.")], ...
    "Scenario selection, timing, event, and actor-count summary.");

buses.RsScenarioSensorStatusBus = makeBus([ ...
    elem("Timestamp",1,"double","s","Synthetic sensor-source sample time."), ...
    elem("ScenarioID",1,"uint16","","Scenario identifier associated with the measurements."), ...
    elem("CameraVisibleCount",1,"uint16","","Actors rendered into the camera image."), ...
    elem("LidarVisibleCount",1,"uint16","","Actors represented in the LiDAR point cloud."), ...
    elem("RadarVisibleCount",1,"uint16","","Actors reported by radar after deterministic missed detections."), ...
    elem("OccludedCount",1,"uint16","","In-range actors suppressed by angular occlusion."), ...
    elem("CameraDropout",1,"boolean","","True during a configured camera dropout window."), ...
    elem("LidarDropout",1,"boolean","","True during a configured LiDAR dropout window."), ...
    elem("RadarDropout",1,"boolean","","True during a configured radar dropout window."), ...
    elem("Valid",1,"boolean","","True when ego, truth, scenario, and generated measurements are usable.")], ...
    "Visibility, occlusion, and dropout evidence from the synthetic scenario sensors.");

buses.RsScenarioEvaluationBus = makeBus([ ...
    elem("Timestamp",1,"double","s","Current evaluation time."), ...
    elem("ScenarioID",1,"uint16","","Scenario being evaluated."), ...
    elem("ElapsedTime",1,"single","s","Elapsed scenario time."), ...
    elem("MinimumClearance",1,"single","m","Minimum truth-based footprint clearance observed so far."), ...
    elem("Collision",1,"boolean","","True once truth footprints overlap."), ...
    elem("GoalReached",1,"boolean","","True once the route adapter reports goal completion."), ...
    elem("ScenarioFinished",1,"boolean","","True once configured scenario duration is reached."), ...
    elem("ReplanCount",1,"uint32","","Number of distinct nonzero plan identifiers observed."), ...
    elem("LastReplanLatency",1,"single","s","Execution time of the newest plan."), ...
    elem("MaximumReplanLatency",1,"single","s","Largest local-planner execution time observed."), ...
    elem("PathSmoothness",1,"single","1/m","Largest RMS absolute curvature observed across valid plans."), ...
    elem("MaximumJerk",1,"single","m/s^3","Largest final-command acceleration slew observed."), ...
    elem("MaximumCrossTrackError",1,"single","m","Largest absolute tracking error observed."), ...
    elem("SafetyInterventionCount",1,"uint32","","Number of safety-override rising edges."), ...
    elem("PipelineReadyRatio",1,"single","","Fraction of evaluated ticks with the complete pipeline ready.",0,1), ...
    elem("SensorDropoutMask",1,"uint8","","Current dropout bits: camera=1, LiDAR=2, radar=4."), ...
    elem("Pass",1,"boolean","","True at scenario finish when every acceptance criterion passes."), ...
    elem("Valid",1,"boolean","","True when evaluation inputs and accumulated metrics are usable.")], ...
    "Truth-isolated closed-loop scenario completion, safety, timing, and comfort metrics.");

parameters = struct;
parameters.RsContractVersion = parameter(uint32(16),"uint32","Shared interface revision.");
parameters.RsMaxDetections = parameter(uint16(limits.MaxDetections),"uint16","Fixed detection-array capacity.");
parameters.RsMaxTracks = parameter(uint16(limits.MaxTracks),"uint16","Fixed track-array capacity.");
parameters.RsMaxPredictionModes = parameter(uint8(limits.MaxPredictionModes),"uint8","Maximum modes per predicted object.");
parameters.RsPredictionSteps = parameter(uint8(limits.PredictionSteps),"uint8","Number of prediction time samples.");
parameters.RsPredictionStep = parameter(single(0.2),"single","Prediction interval in seconds.","s");
parameters.RsPredictionHorizon = parameter(single(3.0),"single","Prediction horizon in seconds.","s");
parameters.RsPredictionHistoryGain = parameter(single(0.35),"single","Update gain for inferred acceleration and yaw rate.");
parameters.RsPredictionVehicleTurnRate = parameter(single(0.25),"single","Alternative vehicle turn-rate magnitude.","rad/s");
parameters.RsPredictionVulnerableTurnRate = parameter(single(0.65),"single","Pedestrian/cyclist/animal alternative turn-rate magnitude.","rad/s");
parameters.RsPredictionVehicleBrake = parameter(single(-3.0),"single","Vehicle braking-mode acceleration.","m/s^2");
parameters.RsPredictionVulnerableBrake = parameter(single(-1.5),"single","Vulnerable-user stopping-mode acceleration.","m/s^2");
parameters.RsPredictionMinimumModeProbability = parameter(single(0.03),"single","Probability floor for active alternative modes.");
parameters.RsMaxPlanPoints = parameter(uint16(limits.MaxPlanPoints),"uint16","Fixed planned-trajectory capacity.");
parameters.RsMaxReferencePoints = parameter(uint16(limits.MaxReferencePoints),"uint16","Fixed reference-path capacity.");
parameters.RsMaxScenarioActors = parameter(uint16(limits.MaxScenarioActors),"uint16","Fixed scenario truth-actor capacity.");
parameters.RsPlanStep = parameter(single(0.10),"single","Local trajectory time interval.","s");
parameters.RsPlanHorizon = parameter(single(6.0),"single","Local trajectory horizon.","s");
parameters.RsPlannerLateralTransitionDistance = parameter(single(10.0),"single", ...
    "Distance used to blend from the route center to a sampled avoidance offset.","m");
parameters.RsPlannerLateralOffsets = parameter(single([-4;-2;-1;0;1;2;4]),"single","Sampled lateral route offsets.","m");
parameters.RsPlannerSpeedScales = parameter(single([0.70;1.00;1.15]),"single","Sampled fractions of behaviour target speed.");
parameters.RsPlannerWheelbase = parameter(single(2.8),"single","Bicycle-model wheelbase.","m");
parameters.RsPlannerVehicleLength = parameter(single(4.6),"single","Ego collision-footprint length.","m");
parameters.RsPlannerVehicleWidth = parameter(single(1.9),"single","Ego collision-footprint width.","m");
parameters.RsPlannerMaximumCurvature = parameter(single(0.22),"single","Maximum feasible absolute path curvature.","1/m");
parameters.RsPlannerMaximumJerk = parameter(single(2.5),"single","Maximum longitudinal jerk magnitude.","m/s^3");
parameters.RsPlannerHardOccupancy = parameter(single(0.65),"single","Static occupancy producing hard collision rejection.");
parameters.RsPlannerCollisionProbability = parameter(single(0.05),"single","Minimum object-mode probability enforced as a hard collision constraint.");
parameters.RsPlannerPredictionSigma = parameter(single(2.0),"single","Prediction covariance inflation used in collision checking.");
parameters.RsPlannerMaximumLongitudinalInflation = parameter(single(3.0),"single","Maximum hard-collision longitudinal uncertainty inflation.","m");
parameters.RsPlannerMaximumLateralInflation = parameter(single(2.5),"single","Maximum hard-collision lateral uncertainty inflation.","m");
parameters.RsPlannerLateralClearanceRatio = parameter(single(0.35),"single","Fraction of following clearance retained as lateral passing clearance.");
parameters.RsPlannerMaximumLateralClearance = parameter(single(0.80),"single","Maximum explicit lateral passing clearance in addition to uncertainty inflation.","m");
parameters.RsPlannerDeadline = parameter(single(0.10),"single","Allowed local-planning latency.","s");
parameters.RsControllerWheelbase = parameter(single(2.8),"single","Trajectory-controller bicycle-model wheelbase.","m");
parameters.RsControllerLateralGain = parameter(single(2.2),"single","Cross-track feedback gain.","1/s");
parameters.RsControllerHeadingGain = parameter(single(1.2),"single","Heading-error feedback gain.");
parameters.RsControllerSofteningSpeed = parameter(single(2.0),"single","Low-speed denominator softening.","m/s");
parameters.RsControllerSpeedKp = parameter(single(0.80),"single","Longitudinal proportional speed gain.","1/s");
parameters.RsControllerSpeedKi = parameter(single(0.15),"single","Longitudinal integral speed gain.","1/s^2");
parameters.RsControllerIntegralLimit = parameter(single(3.0),"single","Absolute speed-error integral limit.","m*s");
parameters.RsControllerMaximumSteering = parameter(single(0.55),"single","Absolute road-wheel steering limit.","rad");
parameters.RsControllerMaximumSteeringRate = parameter(single(0.70),"single","Absolute steering slew rate.","rad/s");
parameters.RsControllerMaximumAcceleration = parameter(single(3.0),"single","Maximum propulsion acceleration request.","m/s^2");
parameters.RsControllerMaximumDeceleration = parameter(single(6.0),"single","Maximum service-braking deceleration magnitude.","m/s^2");
parameters.RsControllerAccelerationSlew = parameter(single(5.0),"single","Normal acceleration-command slew limit.","m/s^3");
parameters.RsControllerPreviewTime = parameter(single(1.0),"single","Time preview used for trajectory reference selection.","s");
parameters.RsControllerPlanGrace = parameter(single(0.25),"single","Allowed age beyond the final plan sample.","s");
parameters.RsVehicleMass = parameter(single(1650),"single","Ego vehicle mass.","kg");
parameters.RsVehicleYawInertia = parameter(single(2800),"single","Ego yaw moment of inertia.","kg*m^2");
parameters.RsVehicleFrontAxleDistance = parameter(single(1.2),"single","Centre-of-mass to front axle.","m");
parameters.RsVehicleRearAxleDistance = parameter(single(1.6),"single","Centre-of-mass to rear axle.","m");
parameters.RsVehicleFrontCorneringStiffness = parameter(single(80000),"single","Front-axle cornering stiffness.","N/rad");
parameters.RsVehicleRearCorneringStiffness = parameter(single(85000),"single","Rear-axle cornering stiffness.","N/rad");
parameters.RsVehicleSteeringTimeConstant = parameter(single(0.08),"single","First-order steering actuator time constant.","s");
parameters.RsVehicleAccelerationTimeConstant = parameter(single(0.15),"single","First-order longitudinal actuator time constant.","s");
parameters.RsVehicleMaximumSteeringRate = parameter(single(1.0),"single","Plant steering-rate limit.","rad/s");
parameters.RsVehicleMaximumJerk = parameter(single(10.0),"single","Plant longitudinal actuator slew limit.","m/s^3");
parameters.RsVehicleLowSpeedThreshold = parameter(single(2.0),"single","Speed below which stabilized kinematic yaw is used.","m/s");
parameters.RsVehicleMaximumSpeed = parameter(single(50.0),"single","Simulation speed safety bound.","m/s");
parameters.RsSafetyEmergencyTTC = parameter(single(1.0),"single","Independent emergency TTC threshold.","s");
parameters.RsSafetyEmergencyDistance = parameter(single(2.5),"single","Immediate forward-clearance emergency threshold.","m");
parameters.RsSafetyControlStaleTime = parameter(single(0.10),"single","Maximum nominal-control age.","s");
parameters.RsSafetyTrackingStaleTime = parameter(single(0.10),"single","Maximum tracking/dynamics status age.","s");
parameters.RsSafetyPerceptionStaleTime = parameter(single(0.25),"single","Maximum map/track age.","s");
parameters.RsSafetyPlanningStaleTime = parameter(single(0.30),"single","Maximum behaviour/planner age.","s");
parameters.RsSafetyCrossTrackWarning = parameter(single(0.75),"single","Cross-track error entering degraded mode.","m");
parameters.RsSafetyCrossTrackFault = parameter(single(2.5),"single","Cross-track error requiring a minimal-risk stop during lane-free avoidance.","m");
parameters.RsSafetyHeadingWarning = parameter(single(0.20),"single","Heading error entering degraded mode.","rad");
parameters.RsSafetyHeadingFault = parameter(single(0.60),"single","Heading error requiring a minimal-risk stop.","rad");
parameters.RsSafetySideslipWarning = parameter(single(0.10),"single","Sideslip entering degraded mode.","rad");
parameters.RsSafetySideslipFault = parameter(single(0.18),"single","Sideslip requiring a minimal-risk stop.","rad");
parameters.RsSafetyFrictionWarning = parameter(single(0.85),"single","Friction utilization entering degraded mode.");
parameters.RsSafetyLateralAccelerationFault = parameter(single(7.0),"single","Lateral acceleration requiring a minimal-risk stop.","m/s^2");
parameters.RsSafetyDegradedSpeed = parameter(single(4.0),"single","Maximum desired speed in degraded mode.","m/s");
parameters.RsSafetyMinimalRiskDeceleration = parameter(single(3.0),"single","Minimal-risk stopping deceleration magnitude.","m/s^2");
parameters.RsSafetyEmergencyHoldTicks = parameter(uint16(50),"uint16","Minimum emergency hold at the 50 Hz control rate.");
parameters.RsSafetyRecoveryTicks = parameter(uint16(25),"uint16","Healthy standstill samples required before release.");
parameters.RsCameraImageHeight = parameter(uint16(limits.CameraImageHeight),"uint16","Camera input image height in pixels.");
parameters.RsCameraImageWidth = parameter(uint16(limits.CameraImageWidth),"uint16","Camera input image width in pixels.");
parameters.RsSemanticOutputHeight = parameter(uint16(limits.SemanticOutputHeight),"uint16","Semantic evidence height in pixels.");
parameters.RsSemanticOutputWidth = parameter(uint16(limits.SemanticOutputWidth),"uint16","Semantic evidence width in pixels.");
parameters.RsSemanticMinConfidence = parameter(single(0.45),"single","Minimum accepted semantic-object confidence.");
parameters.RsSemanticMinBlobArea = parameter(uint32(60),"uint32","Minimum connected-component area in squared network pixels.");
parameters.RsCameraFocalLength = parameter(single([400;400]),"single","Camera focal lengths [fx;fy] in pixels.");
parameters.RsCameraPrincipalPoint = parameter(single([319.5;239.5]),"single","Camera principal point [cx;cy] in pixels.");
parameters.RsCameraHeight = parameter(single(1.4),"single","Camera height above nominal ground.","m");
parameters.RsCameraPitchDown = parameter(single(deg2rad(5)),"single","Positive downward camera pitch.","rad");
parameters.RsScenarioCameraHorizontalFOV = parameter(single(deg2rad(90)),"single","Synthetic camera horizontal field of view.","rad");
parameters.RsScenarioCameraRange = parameter(single(80),"single","Maximum synthetic camera actor range.","m");
parameters.RsTsSemanticInference = parameter(0.10,"double","Semantic network execution period.","s");
parameters.RsMaxLidarPoints = parameter(uint32(limits.MaxLidarPoints),"uint32","Fixed normalized point-cloud capacity.");
parameters.RsLidarZLimits = parameter(single([-3;5]),"single","Accepted vertical LiDAR ROI.","m");
parameters.RsLidarSMRFResolution = parameter(single(0.5),"single","SMRF ground-grid resolution.","m");
parameters.RsLidarSMRFSlopeThreshold = parameter(single(0.20),"single","SMRF maximum local ground slope.");
parameters.RsLidarSMRFElevationThreshold = parameter(single(0.30),"single","SMRF ground elevation threshold.","m");
parameters.RsLidarClusterDistance = parameter(single(0.75),"single","Euclidean cluster separation.","m");
parameters.RsLidarMinClusterPoints = parameter(uint16(8),"uint16","Minimum points accepted as an object cluster.");
parameters.RsLidarMaxClusterPoints = parameter(uint32(20000),"uint32","Maximum points accepted in one object cluster.");
parameters.RsPotholeDepthThreshold = parameter(single(0.08),"single","Minimum surface depression depth.","m");
parameters.RsRoughnessThreshold = parameter(single(0.05),"single","Ground-height roughness producing elevated cost.","m");
parameters.RsTsLidarPerception = parameter(0.10,"double","LiDAR perception execution period.","s");
parameters.RsScenarioLidarRange = parameter(single(70),"single","Maximum synthetic LiDAR actor range.","m");
parameters.RsScenarioRadarRange = parameter(single(150),"single","Maximum synthetic radar actor range.","m");
parameters.RsScenarioRadarPositionSigma = parameter(single([0.35;0.25;0.50]),"single","Synthetic radar Cartesian position standard deviation.","m");
parameters.RsScenarioRadarVelocitySigma = parameter(single([0.40;0.30;0.50]),"single","Synthetic radar Cartesian velocity standard deviation.","m/s");
parameters.RsScenarioMinimumClearance = parameter(single(0.10),"single","Required non-collision truth clearance.","m");
parameters.RsScenarioMaximumReplanLatency = parameter(single(0.10),"single","Maximum accepted local-planner execution time.","s");
parameters.RsScenarioMaximumPathCurvatureRMS = parameter(single(0.18),"single","Maximum accepted RMS path curvature.","1/m");
parameters.RsScenarioMaximumJerk = parameter(single(10.0),"single","Maximum accepted final-command acceleration slew.","m/s^3");
parameters.RsScenarioMaximumCrossTrackError = parameter(single(3.0),"single","Maximum accepted absolute tracking error during lane-free avoidance.","m");
parameters.RsScenarioMinimumReadyRatio = parameter(single(0.70),"single","Minimum accepted fraction of pipeline-ready evaluation ticks.");
parameters.RsFusionCameraLidarGate = parameter(single(4.0),"single","Maximum camera-to-LiDAR pre-association distance.","m");
parameters.RsFusionRadarLidarGate = parameter(single(2.5),"single","Maximum radar-to-LiDAR pre-association distance.","m");
parameters.RsFusionCameraRadarGate = parameter(single(4.5),"single","Maximum camera-to-radar pre-association distance.","m");
parameters.RsFusionTrackAssociationThreshold = parameter(single([12;30]),"single","JPDA assignment and maximum thresholds.");
parameters.RsFusionConfirmationProbability = parameter(single(0.85),"single","JIPDA probability required to confirm a track.");
parameters.RsFusionDeletionProbability = parameter(single(0.005),"single","JIPDA probability below which a track is deleted.");
parameters.RsFusionDetectionProbability = parameter(single(0.80),"single","Conservative per-update detection probability accounting for urban occlusion.");
parameters.RsFusionCoastTime = parameter(single(1.0),"single","Target track persistence through temporary sensor dropout.","s");
parameters.RsMapUnknownDrivability = parameter(single(0.35),"single","Conservative drivability assigned to unobserved cells.");
parameters.RsMapCameraMinConfidence = parameter(single(0.25),"single","Minimum semantic confidence projected onto the ground grid.");
parameters.RsMapCurrentSafetyMargin = parameter(single(0.50),"single","Footprint inflation around current tracked objects.","m");
parameters.RsMapMaximumCurrentInflation = parameter(single(2.0),"single","Maximum covariance-derived current-object map inflation.","m");
parameters.RsMapPredictionSigma = parameter(single(2.5),"single","Gaussian sigma extent rasterized for predicted risk.");
parameters.RsMapMaximumPredictionRadius = parameter(single(8.0),"single","Maximum radius rasterized for a predicted-risk sample.","m");
parameters.RsMapPredictionTimeDecay = parameter(single(3.0),"single","Time constant for future-risk discounting.","s");
parameters.RsMapPotholeThreshold = parameter(single(0.30),"single","Pothole probability that assigns the pothole semantic label.");
parameters.RsBehaviourReactionTime = parameter(single(0.60),"single","Reaction allowance used in stopping distance.","s");
parameters.RsBehaviourEmergencyDeceleration = parameter(single(6.0),"single","Positive emergency-deceleration magnitude.","m/s^2");
parameters.RsBehaviourComfortDeceleration = parameter(single(3.0),"single","Positive comfortable-deceleration magnitude.","m/s^2");
parameters.RsBehaviourEmergencyTTC = parameter(single(1.2),"single","TTC threshold for emergency braking.","s");
parameters.RsBehaviourFollowTimeGap = parameter(single(1.8),"single","Desired following time gap.","s");
parameters.RsBehaviourCreepSpeed = parameter(single(1.2),"single","Occlusion-aware creep speed.","m/s");
parameters.RsBehaviourCautiousSpeed = parameter(single(5.0),"single","Maximum cautious-mode speed.","m/s");
parameters.RsBehaviourAvoidSpeed = parameter(single(4.0),"single","Maximum obstacle-avoidance speed.","m/s");
parameters.RsBehaviourEmergencyHoldTicks = parameter(uint16(5),"uint16","Minimum emergency-mode hold at the planning rate.");
parameters.RsBehaviourYieldClearTicks = parameter(uint16(8),"uint16","Clear samples required before leaving Yield.");
parameters.RsGridResolution = parameter(single(limits.GridResolution),"single","Semantic grid resolution.","m");
parameters.RsGridXLimits = parameter(single(limits.GridXLimits(:)),"single","Grid longitudinal limits.","m");
parameters.RsGridYLimits = parameter(single(limits.GridYLimits(:)),"single","Grid lateral limits.","m");
parameters.RsGridRows = parameter(uint16(limits.GridRows),"uint16","Semantic grid row count.");
parameters.RsGridCols = parameter(uint16(limits.GridCols),"uint16","Semantic grid column count.");
parameters.RsTsBase = parameter(0.01,"double","Fundamental discrete scheduler step.","s");
parameters.RsTsPerception = parameter(0.05,"double","Camera and lidar perception sample time.","s");
parameters.RsTsFusion = parameter(0.05,"double","Sensor-fusion sample time.","s");
parameters.RsTsMap = parameter(0.10,"double","Traversability-map sample time.","s");
parameters.RsTsPrediction = parameter(0.10,"double","Motion-prediction sample time.","s");
parameters.RsTsPlanning = parameter(0.10,"double","Behaviour and local-planning sample time.","s");
parameters.RsTsControl = parameter(0.02,"double","Vehicle-control sample time.","s");
parameters.RsTsScenario = parameter(0.10,"double","Scenario-library and truth update period.","s");

contract = struct("Buses",buses,"Parameters",parameters,"Limits",limits);
end

function bus = makeBus(elements,description)
bus = Simulink.Bus;
bus.Description = description;
bus.DataScope = "Auto";
bus.Alignment = -1;
bus.Elements = elements;
end

function element = elem(name,dimensions,dataType,unit,description,minValue,maxValue)
arguments
    name (1,1) string
    dimensions
    dataType (1,1) string
    unit (1,1) string
    description (1,1) string
    minValue = []
    maxValue = []
end
element = Simulink.BusElement;
element.Name = name;
element.Dimensions = dimensions;
element.DataType = dataType;
element.Unit = unit;
element.Description = description;
element.Complexity = "real";
element.DimensionsMode = "Fixed";
element.Min = minValue;
element.Max = maxValue;
end

function value = parameter(rawValue,dataType,description,unit)
arguments
    rawValue
    dataType (1,1) string
    description (1,1) string
    unit (1,1) string = ""
end
value = Simulink.Parameter(rawValue);
value.DataType = dataType;
value.Description = description;
value.Unit = unit;
value.CoderInfo.StorageClass = "Auto";
end
