function modelPath = createRoadsenseSemanticPerceptionModel()
%CREATEROADSENSESEMANTICPERCEPTIONMODEL Generate the Simulink component.

componentDir = fileparts(mfilename("fullpath"));
root = fileparts(fileparts(componentDir));
modelName = "Roadsense_SemanticPerception";
modelPath = fullfile(componentDir,modelName + ".slx");

addpath(fullfile(root,"Models","SharedData"));
addpath(componentDir);
addpath(fullfile(root,"Data"));
addpath(fullfile(root,"Data","Networks"));
createRoadsenseDataDictionary(fullfile(root,"Data","Roadsense_Data.sldd"));

if bdIsLoaded(modelName)
    close_system(modelName,0);
end
% The SLX is generated output; replace it from this source to keep layout and
% interfaces reproducible and avoid loading stale block definitions.
if isfile(modelPath)
    delete(modelPath);
end
new_system(modelName,"Model");
cleanup = onCleanup(@() closeIfLoaded(modelName));

set_param(modelName, ...
    "DataDictionary","Roadsense_Data.sldd", ...
    "SolverType","Fixed-step", ...
    "Solver","FixedStepDiscrete", ...
    "FixedStep","RsTsBase", ...
    "StopTime","0.1", ...
    "SignalLogging","on");

add_block("simulink/Ports & Subsystems/In1",modelName + "/CameraFrame", ...
    "Position",[30 175 60 195], ...
    "OutDataTypeStr","Bus: RsCameraFrameBus", ...
    "PortDimensions","1","SampleTime","RsTsSemanticInference");
add_block("simulink/Signal Routing/Bus Selector",modelName + "/Camera Frame Selector", ...
    "Position",[105 125 110 245], ...
    "OutputSignals","Timestamp,FrameID,Image,Valid");

systemBlock = modelName + "/Semantic AI and Postprocessor";
add_block("simulink/User-Defined Functions/MATLAB System",systemBlock, ...
    "Position",[205 125 405 270]);
set_param(systemBlock,"System","RoadsenseSemanticPerceptionSystem", ...
    "SimulateUsing","Interpreted execution","InferenceMode","network");

add_block("simulink/Signal Routing/Bus Creator",modelName + "/Semantic Evidence Bus", ...
    "Position",[500 80 510 220], ...
    "Inputs","8", ...
    "OutDataTypeStr","Bus: RsImageSemanticBus");
add_block("simulink/Signal Routing/Bus Creator",modelName + "/Camera Objects Bus", ...
    "Position",[500 260 510 500], ...
    "Inputs","14", ...
    "OutDataTypeStr","Bus: RsCameraObjectListBus");

add_block("simulink/Sources/Constant",modelName + "/Input Image Size", ...
    "Position",[310 455 405 485], ...
    "Value","uint16([RsCameraImageHeight;RsCameraImageWidth])", ...
    "OutDataTypeStr","uint16");

add_block("simulink/Ports & Subsystems/Out1",modelName + "/SemanticEvidence", ...
    "Position",[600 140 630 160], ...
    "OutDataTypeStr","Bus: RsImageSemanticBus");
add_block("simulink/Ports & Subsystems/Out1",modelName + "/CameraObjects", ...
    "Position",[600 355 630 375], ...
    "Port","2", ...
    "OutDataTypeStr","Bus: RsCameraObjectListBus");

add_line(modelName,"CameraFrame/1","Camera Frame Selector/1","autorouting","on");
add_line(modelName,"Camera Frame Selector/3","Semantic AI and Postprocessor/1","autorouting","on");
add_line(modelName,"Camera Frame Selector/4","Semantic AI and Postprocessor/2","autorouting","on");

semanticSources=["Camera Frame Selector/1","Camera Frame Selector/2", ...
    "Semantic AI and Postprocessor/1","Semantic AI and Postprocessor/2", ...
    "Semantic AI and Postprocessor/3","Semantic AI and Postprocessor/11", ...
    "Semantic AI and Postprocessor/12","Semantic AI and Postprocessor/14"];
semanticNames=["Timestamp","FrameID","SemanticLabel","Confidence", ...
    "DrivableProbability","InferenceTime","NetworkReady","Valid"];
connectBus(modelName,semanticSources,"Semantic Evidence Bus",semanticNames);

objectSources=["Camera Frame Selector/1","Camera Frame Selector/2", ...
    "Semantic AI and Postprocessor/4","Semantic AI and Postprocessor/5", ...
    "Semantic AI and Postprocessor/6","Semantic AI and Postprocessor/7", ...
    "Semantic AI and Postprocessor/8","Semantic AI and Postprocessor/9", ...
    "Semantic AI and Postprocessor/10","Input Image Size/1", ...
    "Semantic AI and Postprocessor/11","Semantic AI and Postprocessor/12", ...
    "Semantic AI and Postprocessor/13","Semantic AI and Postprocessor/14"];
objectNames=["Timestamp","FrameID","Count","BoundingBoxes","ClassIDs", ...
    "Scores","Positions","PositionCovariances","ValidMask","InputImageSize", ...
    "InferenceTime","NetworkReady","Overflow","Valid"];
connectBus(modelName,objectSources,"Camera Objects Bus",objectNames);

add_line(modelName,"Semantic Evidence Bus/1","SemanticEvidence/1","autorouting","on");
add_line(modelName,"Camera Objects Bus/1","CameraObjects/1","autorouting","on");

annotation = Simulink.Annotation(modelName, ...
    "Roadsense Semantic Perception" + newline + ...
    "Real neural inference; no actor ground truth");
annotation.Position = [210 30 480 65];

applyRoadsenseModelStyle(modelName);
save_system(modelName,modelPath);
clear cleanup
close_system(modelName,0);
fprintf("Generated %s\n",modelPath);
end

function connectBus(modelName,sources,busName,names)
for index=1:numel(sources)
    line=add_line(modelName,sources(index),busName+"/"+index,"autorouting","on");
    sourceBlock=extractBefore(sources(index),"/"+extractAfter(sources(index),"/"));
    if ~strcmp(get_param(modelName+"/"+sourceBlock,"BlockType"),"BusSelector")
        set_param(line,"Name",names(index));
    end
end
end

function closeIfLoaded(modelName)
if bdIsLoaded(modelName)
    close_system(modelName,0);
end
end
