function modelPath=createRoadsenseSafetySupervisorModel()
%CREATEROADSENSESAFETYSUPERVISORMODEL Generate independent safety command gate.
componentDir=fileparts(mfilename("fullpath")); root=fileparts(fileparts(componentDir));
modelName="Roadsense_SafetySupervisor"; modelPath=fullfile(componentDir,modelName+".slx");
addpath(fullfile(root,"Models","SharedData")); addpath(componentDir); addpath(fullfile(root,"Data"));
createRoadsenseDataDictionary(fullfile(root,"Data","Roadsense_Data.sldd"));
if bdIsLoaded(modelName); close_system(modelName,0); end
if isfile(modelPath); delete(modelPath); end
new_system(modelName,"Model"); cleanup=onCleanup(@() closeIfLoaded(modelName));
set_param(modelName,"DataDictionary","Roadsense_Data.sldd","SolverType","Fixed-step", ...
    "Solver","FixedStepDiscrete","FixedStep","RsTsBase","StopTime","1.0","SignalLogging","on");

names=["EgoState","SemanticGrid","FusedTracks","BehaviourCommand", ...
    "PlannerStatus","TrackingStatus","DynamicsStatus","NominalControl"];
types=["Bus: RsEgoStateBus","Bus: RsSemanticGridBus","Bus: RsFusedTrackListBus", ...
    "Bus: RsBehaviourCommandBus","Bus: RsPlannerStatusBus","Bus: RsTrackingStatusBus", ...
    "Bus: RsVehicleDynamicsStatusBus","Bus: RsVehicleControlBus"];
for index=1:8
    y=100+(index-1)*55;
    add_block("simulink/Ports & Subsystems/In1",modelName+"/"+names(index), ...
        "Position",[20 y 50 y+20],"Port",string(index),"OutDataTypeStr",types(index), ...
        "PortDimensions","1","SampleTime","RsTsControl");
end

assessment=modelName+"/Independent Hazard and Health Assessment";
add_block("simulink/User-Defined Functions/MATLAB System",assessment, ...
    "Position",[125 70 410 535]);
set_param(assessment,"System","RoadsenseSafetyAssessmentSystem", ...
    "MaxTracks","double(RsMaxTracks)","GridRows","double(RsGridRows)", ...
    "GridCols","double(RsGridCols)","GridResolution","RsGridResolution", ...
    "GridXLimits","RsGridXLimits","GridYLimits","RsGridYLimits", ...
    "EmergencyTTC","RsSafetyEmergencyTTC", ...
    "EmergencyDistance","RsSafetyEmergencyDistance", ...
    "ControlStaleTime","RsSafetyControlStaleTime", ...
    "TrackingStaleTime","RsSafetyTrackingStaleTime", ...
    "PerceptionStaleTime","RsSafetyPerceptionStaleTime", ...
    "PlanningStaleTime","RsSafetyPlanningStaleTime", ...
    "CrossTrackWarning","RsSafetyCrossTrackWarning", ...
    "CrossTrackFault","RsSafetyCrossTrackFault", ...
    "HeadingWarning","RsSafetyHeadingWarning","HeadingFault","RsSafetyHeadingFault", ...
    "SideslipWarning","RsSafetySideslipWarning","SideslipFault","RsSafetySideslipFault", ...
    "FrictionWarning","RsSafetyFrictionWarning", ...
    "LateralAccelerationFault","RsSafetyLateralAccelerationFault");
for index=1:8
    line=add_line(modelName,names(index)+"/1", ...
        "Independent Hazard and Health Assessment/"+index,"autorouting","on");
    set_param(line,"Name",names(index));
end

chartPath=modelName+"/Stateflow Safety Latch";
add_block("sflib/Chart",chartPath,"Position",[500 80 700 270]);
buildSafetyChart(chartPath);
for port=1:5
    add_line(modelName,"Independent Hazard and Health Assessment/"+(port+1), ...
        "Stateflow Safety Latch/"+port,"autorouting","on");
end
add_block("simulink/Sources/Constant",modelName+"/Emergency Hold Ticks", ...
    "Position",[430 300 490 325],"Value","RsSafetyEmergencyHoldTicks","OutDataTypeStr","uint16");
add_block("simulink/Sources/Constant",modelName+"/Recovery Ticks", ...
    "Position",[430 345 490 370],"Value","RsSafetyRecoveryTicks","OutDataTypeStr","uint16");
add_line(modelName,"Emergency Hold Ticks/1","Stateflow Safety Latch/6","autorouting","on");
add_line(modelName,"Recovery Ticks/1","Stateflow Safety Latch/7","autorouting","on");

gate=modelName+"/Safety Command Gate";
add_block("simulink/User-Defined Functions/MATLAB System",gate,"Position",[790 65 1065 510]);
set_param(gate,"System","RoadsenseSafetyCommandSystem", ...
    "MaximumSteering","RsControllerMaximumSteering", ...
    "EmergencyDeceleration","RsBehaviourEmergencyDeceleration", ...
    "MinimalRiskDeceleration","RsSafetyMinimalRiskDeceleration", ...
    "DegradedSpeed","RsSafetyDegradedSpeed");
add_line(modelName,"NominalControl/1","Safety Command Gate/1","autorouting","on");
add_line(modelName,"Independent Hazard and Health Assessment/1","Safety Command Gate/2","autorouting","on");
add_line(modelName,"Stateflow Safety Latch/1","Safety Command Gate/3","autorouting","on");
add_line(modelName,"Independent Hazard and Health Assessment/2","Safety Command Gate/4","autorouting","on");
assessmentPorts=[7 8 9 10 11 12 13 14];
for index=1:numel(assessmentPorts)
    add_line(modelName,"Independent Hazard and Health Assessment/"+assessmentPorts(index), ...
        "Safety Command Gate/"+(index+4),"autorouting","on");
end
add_line(modelName,"Stateflow Safety Latch/2","Safety Command Gate/13","autorouting","on");

add_block("simulink/Signal Attributes/Data Type Conversion",modelName+"/Safety State Enum", ...
    "Position",[1120 390 1210 420],"OutDataTypeStr","Enum: RoadsenseTypes.SafetyState");
add_line(modelName,"Safety Command Gate/13","Safety State Enum/1","autorouting","on");
add_block("simulink/Signal Routing/Bus Creator",modelName+"/Safe Control Bus", ...
    "Position",[1270 55 1280 290],"Inputs","10","OutDataTypeStr","Bus: RsVehicleControlBus");
controlNames=["Timestamp","PlanID","SteeringAngle","SteeringRate", ...
    "AccelerationCommand","Throttle","Brake","TargetSpeed","EmergencyStop","Valid"];
for port=1:10
    line=add_line(modelName,"Safety Command Gate/"+port,"Safe Control Bus/"+port,"autorouting","on");
    set_param(line,"Name",controlNames(port));
end

add_block("simulink/Signal Routing/Bus Creator",modelName+"/Safety Status Bus", ...
    "Position",[1270 330 1280 620],"Inputs","14","OutDataTypeStr","Bus: RsSafetyStatusBus");
statusSources=["Safety Command Gate/11","Safety Command Gate/12","Safety State Enum/1", ...
    "Safety Command Gate/14","Safety Command Gate/15","Safety Command Gate/16", ...
    "Safety Command Gate/17","Safety Command Gate/18","Safety Command Gate/19", ...
    "Safety Command Gate/20","Safety Command Gate/21","Safety Command Gate/22", ...
    "Safety Command Gate/23","Safety Command Gate/24"];
statusNames=["Timestamp","SequenceID","State","ReasonMask","MinimumTTC", ...
    "NearestDistance","MaximumInputAge","CrossTrackError","SideslipAngle", ...
    "FrictionUtilization","OverrideActive","EmergencyLatched","SafeToDrive","Valid"];
for port=1:14
    line=add_line(modelName,statusSources(port),"Safety Status Bus/"+port,"autorouting","on");
    set_param(line,"Name",statusNames(port));
end
add_block("simulink/Ports & Subsystems/Out1",modelName+"/SafeVehicleControl", ...
    "Position",[1380 165 1410 185],"OutDataTypeStr","Bus: RsVehicleControlBus");
add_block("simulink/Ports & Subsystems/Out1",modelName+"/SafetyStatus", ...
    "Position",[1380 465 1410 485],"Port","2","OutDataTypeStr","Bus: RsSafetyStatusBus");
add_line(modelName,"Safe Control Bus/1","SafeVehicleControl/1","autorouting","on");
add_line(modelName,"Safety Status Bus/1","SafetyStatus/1","autorouting","on");
annotation=Simulink.Annotation(modelName,"Roadsense Independent Safety Supervisor"+newline+ ...
    "health + freshness + collision + stability assessment -> Stateflow latch -> final command gate");
annotation.Position=[335 15 1060 55];
save_system(modelName,modelPath); clear cleanup; close_system(modelName,0);
fprintf("Generated %s\n",modelPath);
end

function buildSafetyChart(chartPath)
rootObject=sfroot; chart=find(rootObject,"-isa","Stateflow.Chart","Path",char(chartPath));
chart.ActionLanguage="MATLAB";
inputNames={'InputsValid','CriticalFault','EmergencyHazard','DegradedCondition', ...
    'EgoMoving','EmergencyHoldTicks','RecoveryTicks'};
inputTypes={'boolean','boolean','boolean','boolean','boolean','uint16','uint16'};
for index=1:numel(inputNames)
    data=Stateflow.Data(chart); data.Name=inputNames{index}; data.Scope='Input';
    data.Port=index; data.DataType=inputTypes{index};
end
outputs={'StateCode','EmergencyLatched'}; outputTypes={'uint8','boolean'};
for index=1:2
    data=Stateflow.Data(chart); data.Name=outputs{index}; data.Scope='Output';
    data.Port=index; data.DataType=outputTypes{index};
end
locals={'PreviousState','EmergencyCounter','RecoveryCounter'};
localTypes={'uint8','uint16','uint16'};
for index=1:3
    data=Stateflow.Data(chart); data.Name=locals{index}; data.Scope='Local';
    data.DataType=localTypes{index};
end
state=Stateflow.State(chart); state.Name='SafetyDecision'; state.Position=[30 30 395 200];
state.LabelString=sprintf(['SafetyDecision\nentry:\n PreviousState = uint8(0);\n' ...
    ' EmergencyCounter = uint16(0);\n RecoveryCounter = uint16(0);\n' ...
    ' StateCode = uint8(0);\n EmergencyLatched = false;\n' ...
    'during:\n [StateCode, EmergencyCounter, RecoveryCounter, EmergencyLatched] = ...\n' ...
    '  RoadsenseSafetyDecisionCore(InputsValid, CriticalFault, EmergencyHazard, ...\n' ...
    '  DegradedCondition, EgoMoving, PreviousState, EmergencyCounter, ...\n' ...
    '  RecoveryCounter, EmergencyHoldTicks, RecoveryTicks);\n PreviousState = StateCode;']);
transition=Stateflow.Transition(chart); transition.Destination=state;
transition.DestinationOClock=0; transition.SourceEndPoint=[225 10]; transition.MidPoint=[225 20];
end

function closeIfLoaded(modelName)
if bdIsLoaded(modelName); close_system(modelName,0); end
end
