function [ego,map,tracks,behaviour,plannerStatus,tracking,dynamics,nominal]= ...
        createSyntheticRoadsenseSafetyInputs(scenario)
%CREATESYNTHETICROADSENSESAFETYINPUTS Deterministic supervisor cases.
arguments
    scenario (1,1) string {mustBeMember(scenario,["normal","degraded", ...
        "collision","requested","tracking_fault","unstable","stale", ...
        "invalid","deadline","saturation","standstill"])}="normal"
end
[ego,~,plannerStatus]=createSyntheticRoadsenseControllerInputs("aligned");
[~,map,tracks,~]=createSyntheticRoadsenseBehaviourInputs("cruise");
timestamp=ego.Timestamp;
behaviour=struct("Timestamp",timestamp,"SequenceID",uint32(1), ...
    "Mode",RoadsenseTypes.BehaviourMode.Cruise,"TargetSpeed",single(8), ...
    "MaximumAcceleration",single(2),"MinimumAcceleration",single(-3), ...
    "DesiredClearance",single(1),"StopDistance",single(12), ...
    "LeadTrackID",uint32(0),"MinimumTTC",single(inf),"ForwardRisk",single(0.1), ...
    "UnknownFraction",single(0),"ReasonMask",uint16(0), ...
    "ReplanRequested",false,"EmergencyRequested",false,"Valid",true);
nominal=struct("Timestamp",timestamp,"PlanID",plannerStatus.PlanID, ...
    "SteeringAngle",single(0.02),"SteeringRate",single(0), ...
    "AccelerationCommand",single(0.5),"Throttle",single(1/6),"Brake",single(0), ...
    "TargetSpeed",single(8),"EmergencyStop",false,"Valid",true);
tracking=struct("Timestamp",timestamp,"PlanID",plannerStatus.PlanID, ...
    "ReferenceIndex",uint16(2),"CrossTrackError",single(0.05), ...
    "HeadingError",single(0.01),"SpeedError",single(0.1), ...
    "ReferenceCurvature",single(0),"ReferenceAge",single(0.1), ...
    "SteeringSaturated",false,"AccelerationSaturated",false, ...
    "PlanExpired",false,"Valid",true);
dynamics=struct("Timestamp",timestamp,"LongitudinalSpeed",single(5), ...
    "LateralSpeed",single(0),"SideslipAngle",single(0), ...
    "FrontSlipAngle",single(0),"RearSlipAngle",single(0), ...
    "YawAcceleration",single(0),"LongitudinalAcceleration",single(0.5), ...
    "LateralAcceleration",single(0),"FrictionUtilization",single(0.2), ...
    "SteeringState",single(0.02),"ResetApplied",false, ...
    "TireForceSaturated",false,"Valid",true);
plannerStatus.Timestamp=timestamp; plannerStatus.ExecutionTime=single(0.05);
plannerStatus.Deadline=single(0.1); plannerStatus.EmergencyRequested=false;

switch scenario
    case "degraded"
        tracking.CrossTrackError=single(1.0);
    case "collision"
        tracks.Count=uint16(1); tracks.ValidMask(:)=false; tracks.ValidMask(1)=true;
        tracks.TrackIDs(1)=uint32(700); tracks.Positions(1,:)=single([5 0 0.8]);
        tracks.Velocities(1,:)=single([-5 0 0]); tracks.Dimensions(1,:)=single([4 1.8 1.5]);
        tracks.ExistenceProbabilities(1)=single(0.99);
    case "requested"
        plannerStatus.EmergencyRequested=true;
    case "tracking_fault"
        tracking.CrossTrackError=single(6.0);
    case "unstable"
        dynamics.SideslipAngle=single(0.25);
    case "stale"
        map.Timestamp=timestamp-1;
    case "invalid"
        nominal.Valid=false;
    case "deadline"
        plannerStatus.Code=RoadsenseTypes.PlannerCode.DeadlineMiss;
    case "saturation"
        tracking.SteeringSaturated=true;
    case "standstill"
        ego.Velocity(:)=0; dynamics.LongitudinalSpeed=single(0);
end
end
