function modelPath=createRoadsenseVehicleDynamicsModel()
%CREATEROADSENSEVEHICLEDYNAMICSMODEL Generate the dynamic-bicycle plant model.
componentDir=fileparts(mfilename("fullpath")); root=fileparts(fileparts(componentDir));
modelName="Roadsense_VehicleDynamics"; modelPath=fullfile(componentDir,modelName+".slx");
addpath(fullfile(root,"Models","SharedData")); addpath(componentDir); addpath(fullfile(root,"Data"));
createRoadsenseDataDictionary(fullfile(root,"Data","Roadsense_Data.sldd"));
if bdIsLoaded(modelName); close_system(modelName,0); end
if isfile(modelPath); delete(modelPath); end
new_system(modelName,"Model"); cleanup=onCleanup(@() closeIfLoaded(modelName));
set_param(modelName,"DataDictionary","Roadsense_Data.sldd","SolverType","Fixed-step", ...
    "Solver","FixedStepDiscrete","FixedStep","RsTsBase","StopTime","1.0","SignalLogging","on");

names=["VehicleControl","InitialState","RoadCondition","Reset"];
types=["Bus: RsVehicleControlBus","Bus: RsEgoStateBus","Bus: RsRoadConditionBus","boolean"];
for index=1:4
    y=130+(index-1)*80;
    add_block("simulink/Ports & Subsystems/In1",modelName+"/"+names(index), ...
        "Position",[25 y 55 y+20],"Port",string(index),"OutDataTypeStr",types(index), ...
        "PortDimensions","1","SampleTime","RsTsControl");
end

plant=modelName+"/Dynamic Bicycle Vehicle Plant";
add_block("simulink/User-Defined Functions/MATLAB System",plant,"Position",[175 80 485 455]);
set_param(plant,"System","RoadsenseVehicleDynamicsSystem","SampleTime","RsTsControl", ...
    "Mass","RsVehicleMass","YawInertia","RsVehicleYawInertia", ...
    "FrontAxleDistance","RsVehicleFrontAxleDistance", ...
    "RearAxleDistance","RsVehicleRearAxleDistance", ...
    "FrontCorneringStiffness","RsVehicleFrontCorneringStiffness", ...
    "RearCorneringStiffness","RsVehicleRearCorneringStiffness", ...
    "SteeringTimeConstant","RsVehicleSteeringTimeConstant", ...
    "AccelerationTimeConstant","RsVehicleAccelerationTimeConstant", ...
    "MaximumSteering","RsControllerMaximumSteering", ...
    "MaximumSteeringRate","RsVehicleMaximumSteeringRate", ...
    "MaximumAcceleration","RsControllerMaximumAcceleration", ...
    "MaximumDeceleration","RsControllerMaximumDeceleration", ...
    "MaximumJerk","RsVehicleMaximumJerk", ...
    "LowSpeedThreshold","RsVehicleLowSpeedThreshold","MaximumSpeed","RsVehicleMaximumSpeed");
for index=1:4
    line=add_line(modelName,names(index)+"/1","Dynamic Bicycle Vehicle Plant/"+index, ...
        "autorouting","on"); set_param(line,"Name",names(index));
end

add_block("simulink/Signal Routing/Bus Creator",modelName+"/Ego State Bus", ...
    "Position",[610 55 620 300],"Inputs","10","OutDataTypeStr","Bus: RsEgoStateBus");
egoNames=["Timestamp","Position","Velocity","Acceleration","Yaw","Pitch", ...
    "Roll","YawRate","SteeringAngle","Valid"];
for port=1:10
    line=add_line(modelName,"Dynamic Bicycle Vehicle Plant/"+port, ...
        "Ego State Bus/"+port,"autorouting","on"); set_param(line,"Name",egoNames(port));
end

add_block("simulink/Signal Routing/Bus Creator",modelName+"/Dynamics Status Bus", ...
    "Position",[610 330 620 625],"Inputs","14", ...
    "OutDataTypeStr","Bus: RsVehicleDynamicsStatusBus");
statusNames=["Timestamp","LongitudinalSpeed","LateralSpeed","SideslipAngle", ...
    "FrontSlipAngle","RearSlipAngle","YawAcceleration","LongitudinalAcceleration", ...
    "LateralAcceleration","FrictionUtilization","SteeringState","ResetApplied", ...
    "TireForceSaturated","Valid"];
for port=1:14
    line=add_line(modelName,"Dynamic Bicycle Vehicle Plant/"+(port+10), ...
        "Dynamics Status Bus/"+port,"autorouting","on"); set_param(line,"Name",statusNames(port));
end

add_block("simulink/Ports & Subsystems/Out1",modelName+"/EgoState", ...
    "Position",[735 165 765 185],"OutDataTypeStr","Bus: RsEgoStateBus");
add_block("simulink/Ports & Subsystems/Out1",modelName+"/DynamicsStatus", ...
    "Position",[735 475 765 495],"Port","2", ...
    "OutDataTypeStr","Bus: RsVehicleDynamicsStatusBus");
add_line(modelName,"Ego State Bus/1","EgoState/1","autorouting","on");
add_line(modelName,"Dynamics Status Bus/1","DynamicsStatus/1","autorouting","on");

annotation=Simulink.Annotation(modelName,"Roadsense Vehicle Dynamics"+newline+ ...
    "actuator lag -> nonlinear front/rear tyre slip -> friction-circle forces"+newline+ ...
    "dynamic bicycle integration with low-speed stabilization, grade and bank");
annotation.Position=[150 15 755 70];
save_system(modelName,modelPath); clear cleanup; close_system(modelName,0);
fprintf("Generated %s\n",modelPath);
end

function closeIfLoaded(modelName)
if bdIsLoaded(modelName); close_system(modelName,0); end
end
