function modelPath = createRoadsenseSensorFusionModel()
%CREATEROADSENSESENSORFUSIONMODEL Generate the sensor-fusion component.

componentDir = fileparts(mfilename("fullpath"));
root = fileparts(fileparts(componentDir));
modelName = "Roadsense_SensorFusion";
modelPath = fullfile(componentDir,modelName + ".slx");

addpath(fullfile(root,"Models","SharedData"));
addpath(componentDir);
addpath(fullfile(root,"Data"));
createRoadsenseDataDictionary(fullfile(root,"Data","Roadsense_Data.sldd"));

if bdIsLoaded(modelName); close_system(modelName,0); end
if isfile(modelPath); delete(modelPath); end
new_system(modelName,"Model");
cleanup = onCleanup(@() closeIfLoaded(modelName));

set_param(modelName, ...
    "DataDictionary","Roadsense_Data.sldd", ...
    "SolverType","Fixed-step", ...
    "Solver","FixedStepDiscrete", ...
    "FixedStep","RsTsBase", ...
    "StopTime","1.0", ...
    "SignalLogging","on");

add_block("simulink/Ports & Subsystems/In1",modelName + "/CurrentTime", ...
    "Position",[25 95 55 115],"OutDataTypeStr","double", ...
    "SampleTime","RsTsFusion");
add_block("simulink/Ports & Subsystems/In1",modelName + "/CameraObjects", ...
    "Position",[25 165 55 185],"Port","2", ...
    "OutDataTypeStr","Bus: RsCameraObjectListBus","PortDimensions","1", ...
    "SampleTime","RsTsFusion");
add_block("simulink/Ports & Subsystems/In1",modelName + "/LidarObjects", ...
    "Position",[25 235 55 255],"Port","3", ...
    "OutDataTypeStr","Bus: RsLidarObjectListBus","PortDimensions","1", ...
    "SampleTime","RsTsFusion");
add_block("simulink/Ports & Subsystems/In1",modelName + "/RadarObjects", ...
    "Position",[25 305 55 325],"Port","4", ...
    "OutDataTypeStr","Bus: RsRadarObjectListBus","PortDimensions","1", ...
    "SampleTime","RsTsFusion");

fusionBlock = modelName + "/Gated Spatial Fusion and JPDA IMM Tracking";
add_block("simulink/User-Defined Functions/MATLAB System",fusionBlock, ...
    "Position",[180 95 455 340]);
set_param(fusionBlock,"System","RoadsenseSensorFusionSystem", ...
    "SimulateUsing","Interpreted execution");
set_param(fusionBlock, ...
    "MaxDetections","double(RsMaxDetections)", ...
    "MaxTracks","double(RsMaxTracks)", ...
    "NumberClasses","10", ...
    "CameraLidarGate","RsFusionCameraLidarGate", ...
    "RadarLidarGate","RsFusionRadarLidarGate", ...
    "CameraRadarGate","RsFusionCameraRadarGate", ...
    "AssignmentThreshold","RsFusionTrackAssociationThreshold", ...
    "ConfirmationProbability","RsFusionConfirmationProbability", ...
    "DeletionProbability","RsFusionDeletionProbability", ...
    "DetectionProbability","RsFusionDetectionProbability");

add_block("simulink/Signal Routing/Bus Creator",modelName + "/Fused Track Bus", ...
    "Position",[610 65 620 380],"Inputs","21", ...
    "OutDataTypeStr","Bus: RsFusedTrackListBus");
add_block("simulink/Ports & Subsystems/Out1",modelName + "/FusedTracks", ...
    "Position",[720 210 750 230],"OutDataTypeStr","Bus: RsFusedTrackListBus");

add_line(modelName,"CurrentTime/1","Gated Spatial Fusion and JPDA IMM Tracking/1","autorouting","on");
add_line(modelName,"CameraObjects/1","Gated Spatial Fusion and JPDA IMM Tracking/2","autorouting","on");
add_line(modelName,"LidarObjects/1","Gated Spatial Fusion and JPDA IMM Tracking/3","autorouting","on");
add_line(modelName,"RadarObjects/1","Gated Spatial Fusion and JPDA IMM Tracking/4","autorouting","on");
line=add_line(modelName,"CurrentTime/1","Fused Track Bus/1","autorouting","on");
set_param(line,"Name","Timestamp");
trackNames=["Count","TrackIDs","ClassIDs","ClassConfidences", ...
    "ExistenceProbabilities","Positions","Velocities","Accelerations","Yaws", ...
    "YawRates","Dimensions","StateCovariances","Ages","SensorMasks", ...
    "IsConfirmed","ValidMask","ProcessingTime","SourceOverflow","Overflow","Valid"];
for port = 1:20
    line=add_line(modelName,"Gated Spatial Fusion and JPDA IMM Tracking/" + port, ...
        "Fused Track Bus/" + (port+1),"autorouting","on");
    set_param(line,"Name",trackNames(port));
end
add_line(modelName,"Fused Track Bus/1","FusedTracks/1","autorouting","on");

annotation = Simulink.Annotation(modelName, ...
    "Roadsense Sensor Fusion" + newline + ...
    "Camera class + LiDAR extent + radar velocity, followed by JPDA/IMM tracking" + newline + ...
    "Tentative tracks remain exposed for conservative collision checking");
annotation.Position = [170 25 650 72];

applyRoadsenseModelStyle(modelName);
save_system(modelName,modelPath);
clear cleanup
close_system(modelName,0);
fprintf("Generated %s\n",modelPath);
end

function closeIfLoaded(modelName)
if bdIsLoaded(modelName); close_system(modelName,0); end
end
